name: setup rust
runs:
    using: "composite"
    steps:
        - name: install rust
          uses: dtolnay/rust-toolchain@stable

        - name: cache cargo registry
          uses: actions/cache@v3
          continue-on-error: false
          with:
              path: |
                  ~/.cargo/registry
                  ~/.cargo/git
              key: cargo-build-cache

        - name: install wasm-pack
          uses: jetli/wasm-pack-action@v0.4.0
          with:
              version: "latest"

        - name: install zig toolchain
          uses: korandoru/setup-zig@v1
          with:
              zig-version: 0.10.0

        - name: install cargo lambda
          uses: jaxxstorm/action-install-gh-release@v1.9.0
          with:
              repo: cargo-lambda/cargo-lambda
