name: Setup rust and cargo-watch
description: Setup rust and cargo-watch
runs:
    using: "composite"
    steps:
        - name: Install Rust toolchain
          uses: dtolnay/rust-toolchain@stable

        - name: Install Cargo Lambda
          uses: jaxxstorm/action-install-gh-release@v1.9.0
          with:
              repo: cargo-lambda/cargo-lambda
