[workspace]
resolver = "2"
members = [
    "apps/server", "apps/tlds",
    "core",
]

[workspace.package]
license = "MIT"
edition = "2021"
repository = "https://github.com/vloe/shorter"

[workspace.dependencies]
axum = { version = "0.7", default-features = false }
worker = { version = "0.0.21", features = ["http"] }
typeshare = "1.0.0"
