[workspace]
resolver = "2"
members = [
    "apps/server",
    "core",
]

[workspace.package]
license = "MIT"
edition = "2021"
repository = "https://github.com/vloe/shorter"

[workspace.dependencies]
axum = { version = "0.7" }
typeshare = "1.0.0"
