/*
 Generated by typeshare 1.8.0
*/

export interface Tld {
	name: string
	category: string
	manager: string
}

export interface Domain {
	name: string
	available: boolean
}

export interface ShorterParams {
	q: string
}

export interface ShorterRes {
	q: string
}
