/*
 Generated by typeshare 1.11.0
*/

export interface DnsLookupParams {
	q: string
}

export interface DnsLookupRes {
	buyable: boolean
}

export interface Tld {
	buyable: boolean
	category: string
	manager: string
	name: string
}

export interface Domain {
	name: string
	tld: Tld
}

export interface SearchParams {
	q: string
}

export interface SearchRes {
	domains: Domain[]
}
