[package]
name = "sh-server"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
axum = { workspace = true }
worker = { workspace = true }
tower-service = "0.3.2"
console_error_panic_hook = { version = "0.1.1" }
wasm-bindgen-futures = "0.4"
tower-http = { version = "0.5.2", features = ["cors"] }
sh-core = { path = "../../core" }
