[package]
name = "sh-server"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/vloe/shorter"

[dependencies]
axum = "0.7.5"
tokio = { version = "1.39.2", features = [
  "macros",
  "rt-multi-thread",
  "signal",
] }
sqlx = { version = "0.8.1", features = [
  "runtime-tokio-native-tls",
  "postgres",
] }
lambda_http = { version = "0.13.0", optional = true }
tower-http = { version = "0.5.2", features = ["cors"] }
dotenv = "0.15.0"

[features]
lambda = ["dep:lambda_http"]
