[package]
name = "sh-server"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
# sh-crates
sh-core = { path = "../../core" }

# workspace dependencies
axum = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
hickory-resolver = { workspace = true }

# specific server dependencies 
lambda_http = "0.12.0"
tower-http = { version = "0.5.2", features = ["cors"] }
tower = { version = "0.4.13", features = ["limit", "buffer"] }
