[package]
name = "sh-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
lambda_http = "0.13.0"

tokio = { version = "1", features = ["macros"] }
tower-http = { version = "0.6.1", features = ["cors"] }

