[package]
name = "sh-server"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
sh-core = { path = "../../core" }
worker = { version="0.0.21", features=['http'] }
worker-macros = { version="0.0.15", features=['http'] }
axum  = { workspace = true }
tower-service = "0.3.2"
console_error_panic_hook = { version = "0.1.1" }
wasm-bindgen-futures = "0.4"
tower-http = { version="0.5.2", features=["cors"] }

[profile.release]
opt-level = "s" # optimize for size in release builds
lto = true
strip = true
codegen-units = 1
