[package]
name = "sh-server"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
# sh-crates
sh-core = { path = "../../core" }

# workspace dependencies
axum = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
sqlx = { workspace = true, features = ["runtime-tokio-native-tls", "postgres"] }

# specific server dependencies 
lambda_http = { version = "0.13.0", optional = true }
tower-http = { version = "0.5.2", features = ["cors"] }
dotenv = "0.15.0"
openssl = { openssl = "0.10.66", features = ["vendored"] }

[features]
lambda = ["dep:lambda_http"]
