[package]
name = "sh-server"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
lambda_http = "0.10.0"

tokio = { version = "1", features = ["macros"] }

