[package]
name = "sh-server"
version = "0.1.0"
license = "MIT"
edition = "2021"
repository = "https://github.com/vloe/shorter"

[dependencies]
axum = "0.7.5"
tokio = { version = "1.39.2", features = [
  "macros",
  "rt-multi-thread",
  "signal",
] }
lambda_http = { version = "0.13.0", optional = true }

[features]
lambda = ["dep:lambda_http"]
