[package]
name = "sh-server"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
hickory-resolver = { workspace = true }
lambda_http = "0.12.0"
tower-http = { version = "0.5.2", features = ["cors"] }
sh-core = { path = "../../core" }
