/*
 Generated by typeshare 1.8.0
*/

export interface TldInfo {
	category: string
	manager: string
}

export interface Domain {
	isRegistered: boolean
	name: string
	sld: string
	tld: string
	tldInfo: TldInfo
	tldWithDot: string
}

export interface SearchParams {
	q: string
}

export interface SearchRes {
	domains: Domain[]
}
