/*
 Generated by typeshare 1.8.0
*/

export interface ShortenParams {
	domain: string
}

export interface Tld {
	name: string
	category: string
	manager: string
}

export interface Domain {
	name: string
	tld: Tld
	available: boolean
}

export interface ShortenRes {
	domains: Domain[]
}
