/*
 Generated by typeshare 1.8.0
*/

export interface ShortenParams {
	domain: string
}

export interface Tld {
	category: string
	manager: string
	name: string
}

export interface Domain {
	available: boolean
	name: string
	tld: Tld
}

export interface ShortenRes {
	domains: Domain[]
}
