use serde::Serialize;
use typeshare::typeshare;

#[typeshare]
#[derive(Serialize)]
pub(crate) struct Tld {
    pub name: &'static str,
    pub category: &'static str,
    pub manager: &'static str,
}

pub(crate) const TLDS: &[Tld] = &[
    Tld { name: ".able", category: "generic", manager: "Able Inc."},
    Tld { name: ".abogado", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".abudhabi", category: "generic", manager: "Abu Dhabi Systems and Information Centre"},
    Tld { name: ".ac", category: "country-code", manager: "Internet Computer Bureau Limited"},
    Tld { name: ".academy", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".accountant", category: "generic", manager: "dot Accountant Limited"},
    Tld { name: ".accountants", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".actor", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".ad", category: "country-code", manager: "Andorra Telecom"},
    Tld { name: ".ads", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".adult", category: "generic", manager: "ICM Registry AD LLC"},
    Tld { name: ".ae", category: "country-code", manager: "Telecommunications and Digital Government Regulatory Authority (TDRA)"},
    Tld { name: ".af", category: "country-code", manager: "Ministry of Communications and IT"},
    Tld { name: ".africa", category: "generic", manager: "ZA Central Registry NPC trading as Registry.Africa"},
    Tld { name: ".ag", category: "country-code", manager: "UHSA School of Medicine"},
    Tld { name: ".agency", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".ai", category: "country-code", manager: "Government of Anguilla"},
    Tld { name: ".airforce", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".al", category: "country-code", manager: "Electronic and Postal Communications Authority - AKEP"},
    Tld { name: ".alsace", category: "generic", manager: "REGION GRAND EST"},
    Tld { name: ".am", category: "country-code", manager: "Internet Society Non-governmental Organization"},
    Tld { name: ".americanfamily", category: "generic", manager: "AmFam, Inc."},
    Tld { name: ".amfam", category: "generic", manager: "AmFam, Inc."},
    Tld { name: ".amsterdam", category: "generic", manager: "Gemeente Amsterdam"},
    Tld { name: ".an", category: "country-code", manager: "Not assigned"},
    Tld { name: ".analytics", category: "generic", manager: "Campus IP LLC"},
    Tld { name: ".anquan", category: "generic", manager: "QIHOO 360 TECHNOLOGY CO. LTD."},
    Tld { name: ".ao", category: "country-code", manager: "Ministry of Telecommunications and Information Technologies (MTTI)"},
    Tld { name: ".apartments", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".app", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".aq", category: "country-code", manager: "Antarctica Network Information Centre Limited"},
    Tld { name: ".ar", category: "country-code", manager: "Presidencia de la Nación – Secretaría Legal y Técnica"},
    Tld { name: ".arab", category: "generic", manager: "League of Arab States"},
    Tld { name: ".archi", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".army", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".arpa", category: "infrastructure", manager: "Internet Architecture Board (IAB)"},
    Tld { name: ".art", category: "generic", manager: "UK Creative Ideas Limited"},
    Tld { name: ".arte", category: "generic", manager: "Association Relative à la Télévision Européenne G.E.I.E."},
    Tld { name: ".as", category: "country-code", manager: "AS Domain Registry"},
    Tld { name: ".asda", category: "generic", manager: "Wal-Mart Stores, Inc."},
    Tld { name: ".associates", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".at", category: "country-code", manager: "nic.at GmbH"},
    Tld { name: ".athleta", category: "generic", manager: "The Gap, Inc."},
    Tld { name: ".attorney", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".au", category: "country-code", manager: ".au Domain Administration (auDA)"},
    Tld { name: ".auction", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".audible", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".audio", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".author", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".auto", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".autos", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".aw", category: "country-code", manager: "SETAR"},
    Tld { name: ".ax", category: "country-code", manager: "Ålands landskapsregering"},
    Tld { name: ".az", category: "country-code", manager: "IntraNS"},
    Tld { name: ".ba", category: "country-code", manager: "Universtiy Telinformatic Centre (UTIC)"},
    Tld { name: ".baby", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".banamex", category: "generic", manager: "Citigroup Inc."},
    Tld { name: ".band", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".bank", category: "generic", manager: "fTLD Registry Services, LLC"},
    Tld { name: ".bar", category: "generic", manager: "Punto 2012 Sociedad Anonima Promotora de Inversion de Capital Variable"},
    Tld { name: ".barcelona", category: "generic", manager: "Municipi de Barcelona"},
    Tld { name: ".barefoot", category: "generic", manager: "Gallo Vineyards, Inc."},
    Tld { name: ".bargains", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".baseball", category: "generic", manager: "MLB Advanced Media DH, LLC"},
    Tld { name: ".bayern", category: "generic", manager: "Bayern Connect GmbH"},
    Tld { name: ".bb", category: "country-code", manager: "Ministry of Innovation, Science and Smart Technology"},
    Tld { name: ".bcn", category: "generic", manager: "Municipi de Barcelona"},
    Tld { name: ".bd", category: "country-code", manager: "Posts and Telecommunications Division"},
    Tld { name: ".be", category: "country-code", manager: "DNS Belgium vzw/asbl"},
    Tld { name: ".beats", category: "generic", manager: "Beats Electronics, LLC"},
    Tld { name: ".beauty", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".beer", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".berlin", category: "generic", manager: "dotBERLIN GmbH & Co. KG"},
    Tld { name: ".best", category: "generic", manager: "BestTLD Pty Ltd"},
    Tld { name: ".bestbuy", category: "generic", manager: "BBY Solutions, Inc."},
    Tld { name: ".bet", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".bf", category: "country-code", manager: "Autorité de Régulation des Communications Electroniques et des Postes (ARCEP)"},
    Tld { name: ".bg", category: "country-code", manager: "Register.BG"},
    Tld { name: ".bh", category: "country-code", manager: "Telecommunications Regulatory Authority (TRA)"},
    Tld { name: ".bi", category: "country-code", manager: "Centre National de l'Informatique"},
    Tld { name: ".bible", category: "generic", manager: "American Bible Society"},
    Tld { name: ".bid", category: "generic", manager: "dot Bid Limited"},
    Tld { name: ".bike", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".bingo", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".bio", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".biz", category: "generic-restricted", manager: "Registry Services, LLC"},
    Tld { name: ".bj", category: "country-code", manager: "Autorité de Régulation des Communications Electroniques et de la Poste du Bénin (ARCEP BENIN)"},
    Tld { name: ".bl", category: "country-code", manager: "Not assigned"},
    Tld { name: ".black", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".blackfriday", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".blockbuster", category: "generic", manager: "Dish DBS Corporation"},
    Tld { name: ".blog", category: "generic", manager: "Knock Knock WHOIS There, LLC"},
    Tld { name: ".blue", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".bm", category: "country-code", manager: "Registry General Department, Ministry of Home Affairs"},
    Tld { name: ".bn", category: "country-code", manager: "Authority for Info-communications Technology Industry of Brunei Darussalam (AITI)"},
    Tld { name: ".bo", category: "country-code", manager: "Agencia para el Desarrollo de la Información de la Sociedad en Bolivia"},
    Tld { name: ".boats", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".bofa", category: "generic", manager: "Bank of America Corporation"},
    Tld { name: ".bom", category: "generic", manager: "Núcleo de Informação e Coordenação do Ponto BR - NIC.br"},
    Tld { name: ".boo", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".book", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".boston", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".bot", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".boutique", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".box", category: "generic", manager: "Intercap Registry Inc."},
    Tld { name: ".bq", category: "country-code", manager: "Not assigned"},
    Tld { name: ".br", category: "country-code", manager: "Comite Gestor da Internet no Brasil"},
    Tld { name: ".broadway", category: "generic", manager: "Celebrate Broadway, Inc."},
    Tld { name: ".broker", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".brussels", category: "generic", manager: "DNS.be vzw"},
    Tld { name: ".bs", category: "country-code", manager: "University of The Bahamas"},
    Tld { name: ".bt", category: "country-code", manager: "Ministry of Information and Communications"},
    Tld { name: ".build", category: "generic", manager: "Plan Bee LLC"},
    Tld { name: ".builders", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".business", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".buy", category: "generic", manager: "Amazon Registry Services, INC"},
    Tld { name: ".buzz", category: "generic", manager: "DOTSTRATEGY CO."},
    Tld { name: ".bv", category: "country-code", manager: "Norid A/S"},
    Tld { name: ".bw", category: "country-code", manager: "Botswana Communications Regulatory Authority (BOCRA)"},
    Tld { name: ".by", category: "country-code", manager: "Belarusian Cloud Technologies LLC"},
    Tld { name: ".bz", category: "country-code", manager: "University of Belize"},
    Tld { name: ".bzh", category: "generic", manager: "Association www.bzh"},
    Tld { name: ".ca", category: "country-code", manager: "Canadian Internet Registration Authority (CIRA) Autorité Canadienne pour les enregistrements Internet (ACEI)"},
    Tld { name: ".cab", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".cafe", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".call", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".cam", category: "generic", manager: "CAM Connecting SARL"},
    Tld { name: ".camera", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".camp", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".capetown", category: "generic", manager: "ZA Central Registry NPC trading as ZA Central Registry"},
    Tld { name: ".capital", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".car", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".cards", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".care", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".career", category: "generic", manager: "dotCareer LLC"},
    Tld { name: ".careers", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".cars", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".casa", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".case", category: "generic", manager: "Digity, LLC"},
    Tld { name: ".cash", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".casino", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".catering", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".catholic", category: "generic", manager: "Pontificium Consilium de Comunicationibus Socialibus (PCCS) (Pontifical Council for Social Communication)"},
    Tld { name: ".cc", category: "country-code", manager: "eNIC Cocos (Keeling) Islands Pty. Ltd. d/b/a Island Internet Services"},
    Tld { name: ".cd", category: "country-code", manager: "Office Congolais des Postes et Télécommunications - OCPT"},
    Tld { name: ".center", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".ceo", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".cf", category: "country-code", manager: "Societe Centrafricaine de Telecommunications (SOCATEL)"},
    Tld { name: ".cfd", category: "generic", manager: "DOTCFD REGISTRY LTD"},
    Tld { name: ".cg", category: "country-code", manager: "Interpoint Switzerland"},
    Tld { name: ".ch", category: "country-code", manager: "SWITCH The Swiss Education & Research Network"},
    Tld { name: ".channel", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".charity", category: "generic", manager: "Public Interest Registry (PIR)"},
    Tld { name: ".chat", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".cheap", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".christmas", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".church", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".ci", category: "country-code", manager: "Autorité de Régulation des Télécommunications/TIC de Côte d’lvoire (ARTCI)"},
    Tld { name: ".circle", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".city", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".ck", category: "country-code", manager: "Telecom Cook Islands Ltd."},
    Tld { name: ".cl", category: "country-code", manager: "NIC Chile (University of Chile)"},
    Tld { name: ".claims", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".cleaning", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".click", category: "generic", manager: "Internet Naming Co."},
    Tld { name: ".clinic", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".clinique", category: "generic", manager: "The Estée Lauder Companies Inc."},
    Tld { name: ".clothing", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".cloud", category: "generic", manager: "ARUBA PEC S.p.A."},
    Tld { name: ".club", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".cm", category: "country-code", manager: "Agence Nationale des Technologies de l'Information et de la Communication (ANTIC)"},
    Tld { name: ".cn", category: "country-code", manager: "China Internet Network Information Center (CNNIC)"},
    Tld { name: ".co", category: "country-code", manager: "Ministry of Information and Communications Technologies (MinTIC)"},
    Tld { name: ".coach", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".codes", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".coffee", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".college", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".cologne", category: "generic", manager: "dotKoeln GmbH"},
    Tld { name: ".com", category: "generic", manager: "VeriSign Global Registry Services"},
    Tld { name: ".community", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".company", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".compare", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".computer", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".comsec", category: "generic", manager: "VeriSign, Inc."},
    Tld { name: ".condos", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".construction", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".consulting", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".contact", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".contractors", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".cooking", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".cool", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".corsica", category: "generic", manager: "Collectivité de Corse"},
    Tld { name: ".country", category: "generic", manager: "Internet Naming Co."},
    Tld { name: ".coupon", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".coupons", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".courses", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".cpa", category: "generic", manager: "American Institute of Certified Public Accountants"},
    Tld { name: ".cr", category: "country-code", manager: "National Academy of Sciences Academia Nacional de Ciencias"},
    Tld { name: ".credit", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".creditcard", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".cricket", category: "generic", manager: "dot Cricket Limited"},
    Tld { name: ".cruise", category: "generic", manager: "Viking River Cruises (Bermuda) Ltd."},
    Tld { name: ".cruises", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".cu", category: "country-code", manager: "CENIAInternet Industria y San Jose Capitolio Nacional"},
    Tld { name: ".cv", category: "country-code", manager: "Agência Reguladora Multissectorial da Economia (ARME)"},
    Tld { name: ".cw", category: "country-code", manager: "University of Curacao"},
    Tld { name: ".cx", category: "country-code", manager: "Christmas Island Domain Administration Limited"},
    Tld { name: ".cy", category: "country-code", manager: "University of Cyprus"},
    Tld { name: ".cymru", category: "generic", manager: "Nominet UK"},
    Tld { name: ".cyou", category: "generic", manager: "Shortdot SA"},
    Tld { name: ".cz", category: "country-code", manager: "CZ.NIC, z.s.p.o"},
    Tld { name: ".dad", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".dance", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".data", category: "generic", manager: "Dish DBS Corporation"},
    Tld { name: ".date", category: "generic", manager: "dot Date Limited"},
    Tld { name: ".dating", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".day", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".dclk", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".dds", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".de", category: "country-code", manager: "DENIC eG"},
    Tld { name: ".deal", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".deals", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".degree", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".delivery", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".democrat", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".dental", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".dentist", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".desi", category: "generic", manager: "Emergency Back-End Registry Operator Program - ICANN"},
    Tld { name: ".design", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".dev", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".diamonds", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".diet", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".digital", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".direct", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".directory", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".discount", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".diy", category: "generic", manager: "Internet Naming Co."},
    Tld { name: ".dj", category: "country-code", manager: "Djibouti Telecom S.A"},
    Tld { name: ".dk", category: "country-code", manager: "Dansk Internet Forum"},
    Tld { name: ".dm", category: "country-code", manager: "DotDM Corporation"},
    Tld { name: ".do", category: "country-code", manager: "Pontificia Universidad Catolica Madre y Maestra Recinto Santo Tomas de Aquino"},
    Tld { name: ".docs", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".doctor", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".dog", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".domains", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".dot", category: "generic", manager: "Dish DBS Corporation"},
    Tld { name: ".download", category: "generic", manager: "dot Support Limited"},
    Tld { name: ".drive", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".dtv", category: "generic", manager: "Dish DBS Corporation"},
    Tld { name: ".dubai", category: "generic", manager: "Dubai Smart Government Department"},
    Tld { name: ".durban", category: "generic", manager: "ZA Central Registry NPC trading as ZA Central Registry"},
    Tld { name: ".dvr", category: "generic", manager: "Hughes Satellite Systems Corporation"},
    Tld { name: ".dz", category: "country-code", manager: "CERIST"},
    Tld { name: ".earth", category: "generic", manager: "Interlink Systems Innovation Institute K.K."},
    Tld { name: ".eat", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".ec", category: "country-code", manager: "ECUADORDOMAIN S.A."},
    Tld { name: ".eco", category: "generic", manager: "Big Room Inc."},
    Tld { name: ".education", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".ee", category: "country-code", manager: "Eesti Interneti Sihtasutus (EIS)"},
    Tld { name: ".eg", category: "country-code", manager: "Egyptian Universities Network (EUN) Supreme Council of Universities"},
    Tld { name: ".eh", category: "country-code", manager: "Not assigned"},
    Tld { name: ".email", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".energy", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".engineer", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".engineering", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".enterprises", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".equipment", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".er", category: "country-code", manager: "Eritrea Telecommunication Services Corporation (EriTel)"},
    Tld { name: ".es", category: "country-code", manager: "Red.es"},
    Tld { name: ".esq", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".estate", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".et", category: "country-code", manager: "Ethio telecom"},
    Tld { name: ".eu", category: "country-code", manager: "EURid vzw/asbl"},
    Tld { name: ".eus", category: "generic", manager: "Puntueus Fundazioa"},
    Tld { name: ".events", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".exchange", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".expert", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".exposed", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".express", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".fail", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".faith", category: "generic", manager: "dot Faith Limited"},
    Tld { name: ".family", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".fan", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".fans", category: "generic", manager: "ZDNS International Limited"},
    Tld { name: ".farm", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".fashion", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".fast", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".feedback", category: "generic", manager: "Top Level Spectrum, Inc."},
    Tld { name: ".fi", category: "country-code", manager: "Finnish Transport and Communications Agency Traficom"},
    Tld { name: ".fido", category: "generic", manager: "Rogers Communications Canada Inc."},
    Tld { name: ".film", category: "generic", manager: "Motion Picture Domain Registry Pty Ltd"},
    Tld { name: ".final", category: "generic", manager: "Núcleo de Informação e Coordenação do Ponto BR - NIC.br"},
    Tld { name: ".finance", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".financial", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".fire", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".fish", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".fishing", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".fit", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".fitness", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".fj", category: "country-code", manager: "The University of the South Pacific IT Services"},
    Tld { name: ".fk", category: "country-code", manager: "Falkland Islands Government"},
    Tld { name: ".flights", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".florist", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".flowers", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".fly", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".fm", category: "country-code", manager: "FSM Telecommunications Corporation"},
    Tld { name: ".fo", category: "country-code", manager: "FO Council"},
    Tld { name: ".foo", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".food", category: "generic", manager: "Internet Naming Co."},
    Tld { name: ".football", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".forsale", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".forum", category: "generic", manager: "Fegistry, LLC"},
    Tld { name: ".foundation", category: "generic", manager: "Public Interest Registry (PIR)"},
    Tld { name: ".fr", category: "country-code", manager: "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)"},
    Tld { name: ".free", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".frl", category: "generic", manager: "FRLregistry B.V."},
    Tld { name: ".ftr", category: "generic", manager: "Frontier Communications Corporation"},
    Tld { name: ".fun", category: "generic", manager: "Radix Technologies Inc."},
    Tld { name: ".fund", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".furniture", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".futbol", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".fyi", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".ga", category: "country-code", manager: "Agence Nationale des Infrastructures Numériques et des Fréquences (ANINF)"},
    Tld { name: ".gal", category: "generic", manager: "Asociación puntoGAL"},
    Tld { name: ".gallery", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".game", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".games", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".garden", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".gay", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".gb", category: "country-code", manager: "Reserved Domain - IANA"},
    Tld { name: ".gd", category: "country-code", manager: "The National Telecommunications Regulatory Commission (NTRC)"},
    Tld { name: ".gdn", category: "generic", manager: "Joint Stock Company Navigation-information systems"},
    Tld { name: ".ge", category: "country-code", manager: "Caucasus Online LLC"},
    Tld { name: ".gent", category: "generic", manager: "Combell nv"},
    Tld { name: ".george", category: "generic", manager: "Wal-Mart Stores, Inc."},
    Tld { name: ".gf", category: "country-code", manager: "CANAL+ TELECOM"},
    Tld { name: ".gg", category: "country-code", manager: "Island Networks Ltd."},
    Tld { name: ".ggee", category: "generic", manager: "GMO Internet, Inc."},
    Tld { name: ".gh", category: "country-code", manager: "Network Computer Systems Limited"},
    Tld { name: ".gi", category: "country-code", manager: "Sapphire Networks"},
    Tld { name: ".gift", category: "generic", manager: "Uniregistry, Corp."},
    Tld { name: ".gifts", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".gives", category: "generic", manager: "Public Interest Registry (PIR)"},
    Tld { name: ".gl", category: "country-code", manager: "TELE Greenland A/S"},
    Tld { name: ".glass", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".global", category: "generic", manager: "Dot Global Domain Registry Limited"},
    Tld { name: ".gm", category: "country-code", manager: "GM-NIC"},
    Tld { name: ".gmbh", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".gn", category: "country-code", manager: "Centre National des Sciences Halieutiques de Boussoura"},
    Tld { name: ".gold", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".golf", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".goo", category: "generic", manager: "NTT Resonant Inc."},
    Tld { name: ".gop", category: "generic", manager: "Republican State Leadership Committee, Inc."},
    Tld { name: ".got", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".gp", category: "country-code", manager: "Networking Technologies Group"},
    Tld { name: ".gq", category: "country-code", manager: "GETESA"},
    Tld { name: ".gr", category: "country-code", manager: "ICS-FORTH GR"},
    Tld { name: ".graphics", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".gratis", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".green", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".gripe", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".grocery", category: "generic", manager: "Wal-Mart Stores, Inc."},
    Tld { name: ".group", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".gs", category: "country-code", manager: "Government of South Georgia and South Sandwich Islands (GSGSSI)"},
    Tld { name: ".gt", category: "country-code", manager: "Universidad del Valle de Guatemala"},
    Tld { name: ".gu", category: "country-code", manager: "University of Guam"},
    Tld { name: ".guge", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".guide", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".guitars", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".guru", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".gw", category: "country-code", manager: "Autoridade Reguladora Nacional - Tecnologias de Informação e Comunicação da Guiné-Bissau"},
    Tld { name: ".gy", category: "country-code", manager: "University of Guyana"},
    Tld { name: ".hair", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".hamburg", category: "generic", manager: "Hamburg Top-Level-Domain GmbH"},
    Tld { name: ".hangout", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".haus", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".health", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".healthcare", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".help", category: "generic", manager: "Innovation Service Ltd"},
    Tld { name: ".helsinki", category: "generic", manager: "City of Helsinki"},
    Tld { name: ".here", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".hiphop", category: "generic", manager: "Dot Hip Hop, LLC"},
    Tld { name: ".hiv", category: "generic", manager: "Internet Naming Co."},
    Tld { name: ".hk", category: "country-code", manager: "Hong Kong Internet Registration Corporation Ltd."},
    Tld { name: ".hm", category: "country-code", manager: "HM Domain Registry"},
    Tld { name: ".hn", category: "country-code", manager: "Red de Desarrollo Sostenible Honduras"},
    Tld { name: ".hockey", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".holdings", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".holiday", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".homedepot", category: "generic", manager: "Home Depot Product Authority, LLC"},
    Tld { name: ".homegoods", category: "generic", manager: "The TJX Companies, Inc."},
    Tld { name: ".homes", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".homesense", category: "generic", manager: "The TJX Companies, Inc."},
    Tld { name: ".horse", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".hospital", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".host", category: "generic", manager: "Radix Technologies Inc."},
    Tld { name: ".hosting", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".hot", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".hotels", category: "generic", manager: "Booking.com B.V."},
    Tld { name: ".house", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".how", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".hr", category: "country-code", manager: "CARNet - Croatian Academic and Research Network"},
    Tld { name: ".ht", category: "country-code", manager: "Consortium FDS/RDDH"},
    Tld { name: ".hu", category: "country-code", manager: "Council of Hungarian Internet Providers (CHIP)"},
    Tld { name: ".icbc", category: "generic", manager: "Industrial and Commercial Bank of China Limited"},
    Tld { name: ".ice", category: "generic", manager: "IntercontinentalExchange, Inc."},
    Tld { name: ".icu", category: "generic", manager: "Shortdot SA"},
    Tld { name: ".id", category: "country-code", manager: "Perkumpulan Pengelola Nama Domain Internet Indonesia (PANDI)"},
    Tld { name: ".ie", category: "country-code", manager: "University College Dublin Computing Services Computer Centre"},
    Tld { name: ".il", category: "country-code", manager: "The Israel Internet Association (RA)"},
    Tld { name: ".im", category: "country-code", manager: "Isle of Man Government"},
    Tld { name: ".imamat", category: "generic", manager: "Fondation Aga Khan (Aga Khan Foundation)"},
    Tld { name: ".immo", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".immobilien", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".in", category: "country-code", manager: "National Internet Exchange of India"},
    Tld { name: ".inc", category: "generic", manager: "Intercap Registry Inc."},
    Tld { name: ".industries", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".info", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".ing", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".ink", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".institute", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".insurance", category: "generic", manager: "fTLD Registry Services LLC"},
    Tld { name: ".insure", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".international", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".investments", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".io", category: "country-code", manager: "Internet Computer Bureau Limited"},
    Tld { name: ".iq", category: "country-code", manager: "Communications and Media Commission (CMC)"},
    Tld { name: ".ir", category: "country-code", manager: "Institute for Research in Fundamental Sciences"},
    Tld { name: ".irish", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".is", category: "country-code", manager: "ISNIC - Internet Iceland ltd."},
    Tld { name: ".ismaili", category: "generic", manager: "Fondation Aga Khan (Aga Khan Foundation)"},
    Tld { name: ".ist", category: "generic", manager: "Istanbul Metropolitan Municipality"},
    Tld { name: ".istanbul", category: "generic", manager: "Istanbul Metropolitan Municipality"},
    Tld { name: ".it", category: "country-code", manager: "IIT - CNR"},
    Tld { name: ".je", category: "country-code", manager: "Island Networks (Jersey) Ltd."},
    Tld { name: ".jetzt", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".jewelry", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".jio", category: "generic", manager: "Affinity Names, Inc."},
    Tld { name: ".jll", category: "generic", manager: "Jones Lang LaSalle Incorporated"},
    Tld { name: ".jm", category: "country-code", manager: "University of West Indies"},
    Tld { name: ".jmp", category: "generic", manager: "Matrix IP LLC"},
    Tld { name: ".jnj", category: "generic", manager: "Johnson & Johnson Services, Inc."},
    Tld { name: ".jo", category: "country-code", manager: "Ministry of Digital Economy and Entrepreneurship (MoDEE)"},
    Tld { name: ".joburg", category: "generic", manager: "ZA Central Registry NPC trading as ZA Central Registry"},
    Tld { name: ".jot", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".joy", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".jp", category: "country-code", manager: "Japan Registry Services Co., Ltd."},
    Tld { name: ".jprs", category: "generic", manager: "Japan Registry Services Co., Ltd."},
    Tld { name: ".juegos", category: "generic", manager: "Internet Naming Company LLC"},
    Tld { name: ".kaufen", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".ke", category: "country-code", manager: "Kenya Network Information Center (KeNIC)"},
    Tld { name: ".kg", category: "country-code", manager: "AsiaInfo Telecommunication Enterprise"},
    Tld { name: ".kh", category: "country-code", manager: "Telecommunication Regulator of Cambodia (TRC)"},
    Tld { name: ".ki", category: "country-code", manager: "Ministry of Information, Communications and Transport (MICT)"},
    Tld { name: ".kids", category: "generic", manager: "DotKids Foundation Limited"},
    Tld { name: ".kim", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".kitchen", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".kiwi", category: "generic", manager: "DOT KIWI LIMITED"},
    Tld { name: ".km", category: "country-code", manager: "Comores Telecom"},
    Tld { name: ".kn", category: "country-code", manager: "Ministry of Finance, Sustainable Development Information & Technology"},
    Tld { name: ".koeln", category: "generic", manager: "dotKoeln GmbH"},
    Tld { name: ".kosher", category: "generic", manager: "Kosher Marketing Assets LLC"},
    Tld { name: ".kp", category: "country-code", manager: "Star Joint Venture Company"},
    Tld { name: ".kpn", category: "generic", manager: "Koninklijke KPN N.V."},
    Tld { name: ".kr", category: "country-code", manager: "Korea Internet & Security Agency (KISA)"},
    Tld { name: ".krd", category: "generic", manager: "KRG Department of Information Technology"},
    Tld { name: ".kw", category: "country-code", manager: "Communications and Information Technology Regulatory Authority"},
    Tld { name: ".ky", category: "country-code", manager: "Utility Regulation and Competition Office (OfReg)"},
    Tld { name: ".kyoto", category: "generic", manager: "Academic Institution: Kyoto Jyoho Gakuen"},
    Tld { name: ".kz", category: "country-code", manager: "Association of IT Companies of Kazakhstan"},
    Tld { name: ".la", category: "country-code", manager: "Lao National Internet Center (LANIC), Ministry of Technology and Communications"},
    Tld { name: ".lamer", category: "generic", manager: "The Estée Lauder Companies Inc."},
    Tld { name: ".land", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".lat", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".latino", category: "generic", manager: "Dish DBS Corporation"},
    Tld { name: ".law", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".lawyer", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".lb", category: "country-code", manager: "Internet Society Lebanon"},
    Tld { name: ".lc", category: "country-code", manager: "University of Puerto Rico"},
    Tld { name: ".lease", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".lefrak", category: "generic", manager: "LeFrak Organization, Inc."},
    Tld { name: ".legal", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".lgbt", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".li", category: "country-code", manager: "SWITCH The Swiss Education & Research Network"},
    Tld { name: ".life", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".lifeinsurance", category: "generic", manager: "American Council of Life Insurers"},
    Tld { name: ".lighting", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".like", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".limited", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".limo", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".link", category: "generic", manager: "Nova Registry Ltd."},
    Tld { name: ".live", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".living", category: "generic", manager: "Internet Naming Co."},
    Tld { name: ".lk", category: "country-code", manager: "Council for Information Technology LK Domain Registrar"},
    Tld { name: ".llc", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".llp", category: "generic", manager: "Intercap Registry Inc."},
    Tld { name: ".loan", category: "generic", manager: "dot Loan Limited"},
    Tld { name: ".loans", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".locker", category: "generic", manager: "Orange Domains LLC"},
    Tld { name: ".lol", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".london", category: "generic", manager: "Dot London Domains Limited"},
    Tld { name: ".lotto", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".love", category: "generic", manager: "Merchant Law Group LLP"},
    Tld { name: ".lr", category: "country-code", manager: "Data Technology Solutions, Inc."},
    Tld { name: ".ls", category: "country-code", manager: "Lesotho Network Information Centre Proprietary (LSNIC)"},
    Tld { name: ".lt", category: "country-code", manager: "Kaunas University of Technology"},
    Tld { name: ".ltd", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".ltda", category: "generic", manager: "InterNetX Corp."},
    Tld { name: ".lu", category: "country-code", manager: "RESTENA"},
    Tld { name: ".luxe", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".luxury", category: "generic", manager: "Luxury Partners LLC"},
    Tld { name: ".lv", category: "country-code", manager: "University of Latvia Institute of Mathematics and Computer Science Department of Network Solutions (DNS)"},
    Tld { name: ".ly", category: "country-code", manager: "General Post and Telecommunication Company"},
    Tld { name: ".ma", category: "country-code", manager: "Agence Nationale de Réglementation des Télécommunications (ANRT)"},
    Tld { name: ".madrid", category: "generic", manager: "Comunidad de Madrid"},
    Tld { name: ".maison", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".makeup", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".management", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".map", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".market", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".marketing", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".markets", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".marshalls", category: "generic", manager: "The TJX Companies, Inc."},
    Tld { name: ".mba", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".mc", category: "country-code", manager: "Direction des Plateformes et des Ressources Numériques"},
    Tld { name: ".md", category: "country-code", manager: "IP Serviciul Tehnologia Informatiei si Securitate Cibernetica"},
    Tld { name: ".me", category: "country-code", manager: "Government of Montenegro"},
    Tld { name: ".med", category: "generic", manager: "Medistry LLC"},
    Tld { name: ".media", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".meet", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".melbourne", category: "generic", manager: "The Crown in right of the State of Victoria, represented by its Department of State Development, Business and Innovation"},
    Tld { name: ".meme", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".memorial", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".men", category: "generic", manager: "Exclusive Registry Limited"},
    Tld { name: ".menu", category: "generic", manager: "Dot Menu Registry LLC"},
    Tld { name: ".merckmsd", category: "generic", manager: "MSD Registry Holdings, Inc."},
    Tld { name: ".mf", category: "country-code", manager: "Not assigned"},
    Tld { name: ".mg", category: "country-code", manager: "NIC-MG (Network Information Center Madagascar)"},
    Tld { name: ".mh", category: "country-code", manager: "Office of the Cabinet"},
    Tld { name: ".miami", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".mint", category: "generic", manager: "Intuit Administrative Services, Inc."},
    Tld { name: ".mk", category: "country-code", manager: "Macedonian Academic Research Network Skopje"},
    Tld { name: ".ml", category: "country-code", manager: "Agence des Technologies de l’Information et de la Communication"},
    Tld { name: ".mls", category: "generic", manager: "The Canadian Real Estate Association"},
    Tld { name: ".mm", category: "country-code", manager: "Ministry of Transport and Communications"},
    Tld { name: ".mn", category: "country-code", manager: "Datacom Co., Ltd."},
    Tld { name: ".mo", category: "country-code", manager: "Macao Post and Telecommunications Bureau (CTT)"},
    Tld { name: ".mobi", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".mobile", category: "generic", manager: "Dish DBS Corporation"},
    Tld { name: ".moda", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".moe", category: "generic", manager: "Interlink Systems Innovation Institute K.K."},
    Tld { name: ".moi", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".mom", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".money", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".monster", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".mortgage", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".moscow", category: "generic", manager: "Foundation for Assistance for Internet Technologies and Infrastructure Development (FAITID)"},
    Tld { name: ".motorcycles", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".mov", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".movie", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".mp", category: "country-code", manager: "Saipan Datacom, Inc."},
    Tld { name: ".mq", category: "country-code", manager: "CANAL+ TELECOM"},
    Tld { name: ".mr", category: "country-code", manager: "Université de Nouakchott Al Aasriya"},
    Tld { name: ".ms", category: "country-code", manager: "MNI Networks Ltd."},
    Tld { name: ".mt", category: "country-code", manager: "NIC (Malta)"},
    Tld { name: ".mu", category: "country-code", manager: "Internet Direct Ltd"},
    Tld { name: ".music", category: "generic", manager: "DotMusic Limited"},
    Tld { name: ".mv", category: "country-code", manager: "Dhiraagu Pvt. Ltd. (DHIVEHINET)"},
    Tld { name: ".mw", category: "country-code", manager: "Malawi Sustainable Development Network Programme (Malawi SDNP)"},
    Tld { name: ".mx", category: "country-code", manager: "NIC-Mexico ITESM - Campus Monterrey"},
    Tld { name: ".my", category: "country-code", manager: "MYNIC Berhad"},
    Tld { name: ".mz", category: "country-code", manager: "Centro de Informatica de Universidade Eduardo Mondlane"},
    Tld { name: ".na", category: "country-code", manager: "Namibian Network Information Center"},
    Tld { name: ".nab", category: "generic", manager: "National Australia Bank Limited"},
    Tld { name: ".nagoya", category: "generic", manager: "GMO Registry, Inc."},
    Tld { name: ".name", category: "generic-restricted", manager: "VeriSign Information Services, Inc."},
    Tld { name: ".navy", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".nc", category: "country-code", manager: "Office des Postes et Telecommunications"},
    Tld { name: ".ne", category: "country-code", manager: "SONITEL"},
    Tld { name: ".net", category: "generic", manager: "VeriSign Global Registry Services"},
    Tld { name: ".netbank", category: "generic", manager: "COMMONWEALTH BANK OF AUSTRALIA"},
    Tld { name: ".network", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".new", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".news", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".next", category: "generic", manager: "Next plc"},
    Tld { name: ".nextdirect", category: "generic", manager: "Next plc"},
    Tld { name: ".nexus", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".nf", category: "country-code", manager: "Norfolk Island Data Services"},
    Tld { name: ".ng", category: "country-code", manager: "Nigeria Internet Registration Association"},
    Tld { name: ".ngo", category: "generic", manager: "Public Interest Registry"},
    Tld { name: ".ni", category: "country-code", manager: "Universidad Nacional del Ingernieria Centro de Computo"},
    Tld { name: ".ninja", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".nl", category: "country-code", manager: "SIDN (Stichting Internet Domeinregistratie Nederland)"},
    Tld { name: ".no", category: "country-code", manager: "Norid A/S"},
    Tld { name: ".now", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".nowruz", category: "generic", manager: "Asia Green IT System Bilgisayar San. ve Tic. Ltd. Sti."},
    Tld { name: ".nowtv", category: "generic", manager: "Starbucks (HK) Limited"},
    Tld { name: ".np", category: "country-code", manager: "Mercantile Communications Pvt. Ltd."},
    Tld { name: ".nr", category: "country-code", manager: "CENPAC NET"},
    Tld { name: ".nrw", category: "generic", manager: "Minds + Machines GmbH"},
    Tld { name: ".nu", category: "country-code", manager: "The IUSN Foundation"},
    Tld { name: ".nyc", category: "generic", manager: "The City of New York by and through the New York City Department of Information Technology & Telecommunications"},
    Tld { name: ".nz", category: "country-code", manager: "InternetNZ"},
    Tld { name: ".observer", category: "generic", manager: "Fegistry, LLC"},
    Tld { name: ".okinawa", category: "generic", manager: "BRregistry, Inc."},
    Tld { name: ".olayan", category: "generic", manager: "Crescent Holding GmbH"},
    Tld { name: ".olayangroup", category: "generic", manager: "Crescent Holding GmbH"},
    Tld { name: ".ollo", category: "generic", manager: "Dish DBS Corporation"},
    Tld { name: ".om", category: "country-code", manager: "Telecommunications Regulatory Authority (TRA)"},
    Tld { name: ".one", category: "generic", manager: "One.com A/S"},
    Tld { name: ".ong", category: "generic", manager: "Public Interest Registry"},
    Tld { name: ".onl", category: "generic", manager: "iRegistry GmbH"},
    Tld { name: ".online", category: "generic", manager: "Radix Technologies Inc."},
    Tld { name: ".ooo", category: "generic", manager: "INFIBEAM INCORPORATION LIMITED"},
    Tld { name: ".open", category: "generic", manager: "American Express Travel Related Services Company, Inc."},
    Tld { name: ".org", category: "generic", manager: "Public Interest Registry (PIR)"},
    Tld { name: ".organic", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".origins", category: "generic", manager: "The Estée Lauder Companies Inc."},
    Tld { name: ".osaka", category: "generic", manager: "Osaka Registry Co., Ltd."},
    Tld { name: ".ott", category: "generic", manager: "Dish DBS Corporation"},
    Tld { name: ".pa", category: "country-code", manager: "Universidad Tecnologica de Panama"},
    Tld { name: ".page", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".paris", category: "generic", manager: "City of Paris"},
    Tld { name: ".pars", category: "generic", manager: "Asia Green IT System Bilgisayar San. ve Tic. Ltd. Sti."},
    Tld { name: ".partners", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".parts", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".party", category: "generic", manager: "Blue Sky Registry Limited"},
    Tld { name: ".pay", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".pe", category: "country-code", manager: "Red Cientifica Peruana"},
    Tld { name: ".pet", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".pf", category: "country-code", manager: "Gouvernement de la Polynésie française"},
    Tld { name: ".pg", category: "country-code", manager: "PNG DNS Administration Vice Chancellors Office The Papua New Guinea University of Technology"},
    Tld { name: ".ph", category: "country-code", manager: "PH Domain Foundation"},
    Tld { name: ".pharmacy", category: "generic", manager: "National Association of Boards of Pharmacy"},
    Tld { name: ".phd", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".phone", category: "generic", manager: "Dish DBS Corporation"},
    Tld { name: ".photo", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".photography", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".photos", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".physio", category: "generic", manager: "PhysBiz Pty Ltd"},
    Tld { name: ".pics", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".pictures", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".pid", category: "generic", manager: "Top Level Spectrum, Inc."},
    Tld { name: ".pin", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".pink", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".pizza", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".pk", category: "country-code", manager: "PKNIC"},
    Tld { name: ".pl", category: "country-code", manager: "Research and Academic Computer Network"},
    Tld { name: ".place", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".plumbing", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".plus", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".pm", category: "country-code", manager: "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)"},
    Tld { name: ".pn", category: "country-code", manager: "Pitcairn Island Administration"},
    Tld { name: ".pnc", category: "generic", manager: "PNC Domain Co., LLC"},
    Tld { name: ".poker", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".pr", category: "country-code", manager: "Gauss Research Laboratory Inc."},
    Tld { name: ".pramerica", category: "generic", manager: "Prudential Financial, Inc."},
    Tld { name: ".press", category: "generic", manager: "Radix Technologies Inc."},
    Tld { name: ".prime", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".pro", category: "generic-restricted", manager: "Identity Digital Limited"},
    Tld { name: ".productions", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".prof", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".promo", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".properties", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".property", category: "generic", manager: "Digital Property Infrastructure Limited"},
    Tld { name: ".protection", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".ps", category: "country-code", manager: "Ministry Of Telecommunications & Information Technology, Government Computer Center."},
    Tld { name: ".pt", category: "country-code", manager: "Associação DNS.PT"},
    Tld { name: ".pub", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".pw", category: "country-code", manager: "Micronesia Investment and Development Corporation"},
    Tld { name: ".py", category: "country-code", manager: "NIC-PY"},
    Tld { name: ".qa", category: "country-code", manager: "Communications Regulatory Authority"},
    Tld { name: ".qpon", category: "generic", manager: "DOTQPON LLC."},
    Tld { name: ".quebec", category: "generic", manager: "PointQuébec Inc"},
    Tld { name: ".racing", category: "generic", manager: "Premier Registry Limited"},
    Tld { name: ".radio", category: "generic", manager: "European Broadcasting Union (EBU)"},
    Tld { name: ".re", category: "country-code", manager: "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)"},
    Tld { name: ".read", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".realestate", category: "generic", manager: "dotRealEstate LLC"},
    Tld { name: ".realtor", category: "generic", manager: "Real Estate Domains LLC"},
    Tld { name: ".realty", category: "generic", manager: "Internet Naming Co."},
    Tld { name: ".recipes", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".red", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".redumbrella", category: "generic", manager: "Travelers TLD, LLC"},
    Tld { name: ".rehab", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".reise", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".reisen", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".reit", category: "generic", manager: "National Association of Real Estate Investment Trusts, Inc."},
    Tld { name: ".ren", category: "generic", manager: "ZDNS International Limited"},
    Tld { name: ".rent", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".rentals", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".repair", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".report", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".republican", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".rest", category: "generic", manager: "Punto 2012 Sociedad Anonima Promotora de Inversion de Capital Variable"},
    Tld { name: ".restaurant", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".review", category: "generic", manager: "dot Review Limited"},
    Tld { name: ".reviews", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".rich", category: "generic", manager: "iRegistry GmbH"},
    Tld { name: ".richardli", category: "generic", manager: "Pacific Century Asset Management (HK) Limited"},
    Tld { name: ".ril", category: "generic", manager: "Reliance Industries Limited"},
    Tld { name: ".rio", category: "generic", manager: "Empresa Municipal de Informática SA - IPLANRIO"},
    Tld { name: ".rip", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".ro", category: "country-code", manager: "National Institute for R&D in Informatics"},
    Tld { name: ".rocks", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".rodeo", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".room", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".rs", category: "country-code", manager: "Serbian National Internet Domain Registry (RNIDS)"},
    Tld { name: ".rsvp", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".ru", category: "country-code", manager: "Coordination Center for TLD RU"},
    Tld { name: ".rugby", category: "generic", manager: "World Rugby Strategic Developments Limited"},
    Tld { name: ".ruhr", category: "generic", manager: "dotSaarland GmbH"},
    Tld { name: ".run", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".rw", category: "country-code", manager: "Rwanda Internet Community and Technology Alliance (RICTA) Ltd"},
    Tld { name: ".ryukyu", category: "generic", manager: "BRregistry, Inc."},
    Tld { name: ".sa", category: "country-code", manager: "Communications, Space and Technology Commission"},
    Tld { name: ".saarland", category: "generic", manager: "dotSaarland GmbH"},
    Tld { name: ".safe", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".sale", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".salon", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".samsclub", category: "generic", manager: "Wal-Mart Stores, Inc."},
    Tld { name: ".sarl", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".save", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".sb", category: "country-code", manager: "Solomon Telekom Company Limited"},
    Tld { name: ".sc", category: "country-code", manager: "VCS Pty Ltd"},
    Tld { name: ".scholarships", category: "generic", manager: "Scholarships.com, LLC"},
    Tld { name: ".school", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".schule", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".science", category: "generic", manager: "dot Science Limited"},
    Tld { name: ".scot", category: "generic", manager: "Dot Scot Registry Limited"},
    Tld { name: ".sd", category: "country-code", manager: "Sudan Internet Society"},
    Tld { name: ".se", category: "country-code", manager: "The Internet Infrastructure Foundation"},
    Tld { name: ".search", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".secure", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".security", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".select", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".services", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".sg", category: "country-code", manager: "Singapore Network Information Centre (SGNIC) Pte Ltd"},
    Tld { name: ".sh", category: "country-code", manager: "Government of St. Helena"},
    Tld { name: ".shia", category: "generic", manager: "Asia Green IT System Bilgisayar San. ve Tic. Ltd. Sti."},
    Tld { name: ".shiksha", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".shoes", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".shop", category: "generic", manager: "GMO Registry, Inc."},
    Tld { name: ".shopping", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".shouji", category: "generic", manager: "QIHOO 360 TECHNOLOGY CO. LTD."},
    Tld { name: ".show", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".si", category: "country-code", manager: "Academic and Research Network of Slovenia (ARNES)"},
    Tld { name: ".silk", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".singles", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".site", category: "generic", manager: "Radix Technologies Inc."},
    Tld { name: ".sj", category: "country-code", manager: "Norid A/S"},
    Tld { name: ".sk", category: "country-code", manager: "SK-NIC, a.s."},
    Tld { name: ".ski", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".skin", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".sl", category: "country-code", manager: "Sierratel"},
    Tld { name: ".sling", category: "generic", manager: "Hughes Satellite Systems Corporation"},
    Tld { name: ".sm", category: "country-code", manager: "Telecom Italia San Marino S.p.A."},
    Tld { name: ".smile", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".sn", category: "country-code", manager: "Universite Cheikh Anta Diop"},
    Tld { name: ".so", category: "country-code", manager: "Ministry of Post and Telecommunications"},
    Tld { name: ".soccer", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".social", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".software", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".solar", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".solutions", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".song", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".soy", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".spa", category: "generic", manager: "Asia Spa and Wellness Promotion Council Limited"},
    Tld { name: ".space", category: "generic", manager: "Radix Technologies Inc."},
    Tld { name: ".sport", category: "generic", manager: "SportAccord"},
    Tld { name: ".spot", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".sr", category: "country-code", manager: "Telesur"},
    Tld { name: ".srl", category: "generic", manager: "InterNetX Corp."},
    Tld { name: ".ss", category: "country-code", manager: "National Communication Authority (NCA)"},
    Tld { name: ".st", category: "country-code", manager: "Tecnisys"},
    Tld { name: ".stockholm", category: "generic", manager: "Stockholms kommun"},
    Tld { name: ".storage", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".store", category: "generic", manager: "Radix Technologies Inc."},
    Tld { name: ".stream", category: "generic", manager: "dot Stream Limited"},
    Tld { name: ".studio", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".study", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".style", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".su", category: "country-code", manager: "Russian Institute for Development of Public Networks (ROSNIIROS)"},
    Tld { name: ".sucks", category: "generic", manager: "Vox Populi Registry Ltd."},
    Tld { name: ".supplies", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".supply", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".support", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".surf", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".surgery", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".sv", category: "country-code", manager: "SVNet"},
    Tld { name: ".swiss", category: "generic", manager: "Swiss Confederation"},
    Tld { name: ".sx", category: "country-code", manager: "SX Registry SA B.V."},
    Tld { name: ".sy", category: "country-code", manager: "National Agency for Network Services (NANS)"},
    Tld { name: ".sydney", category: "generic", manager: "State of New South Wales, Department of Premier and Cabinet"},
    Tld { name: ".systems", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".sz", category: "country-code", manager: "University of Swaziland Department of Computer Science"},
    Tld { name: ".tab", category: "generic", manager: "Tabcorp Holdings Limited"},
    Tld { name: ".taipei", category: "generic", manager: "Taipei City Government"},
    Tld { name: ".talk", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".tatar", category: "generic", manager: "Limited Liability Company Coordination Center of Regional Domain of Tatarstan Republic"},
    Tld { name: ".tattoo", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".tax", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".taxi", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".tc", category: "country-code", manager: "Melrex TC"},
    Tld { name: ".tci", category: "generic", manager: "Asia Green IT System Bilgisayar San. ve Tic. Ltd. Sti."},
    Tld { name: ".td", category: "country-code", manager: "l'Agence de Développement des Technologies de l'Information et de la Communication (ADETIC)"},
    Tld { name: ".team", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".tech", category: "generic", manager: "Radix Technologies Inc."},
    Tld { name: ".technology", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".tennis", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".tf", category: "country-code", manager: "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)"},
    Tld { name: ".tg", category: "country-code", manager: "Autorité de Régulation des Communications Electroniques et des Postes (ARCEP)"},
    Tld { name: ".th", category: "country-code", manager: "Thai Network Information Center Foundation"},
    Tld { name: ".thd", category: "generic", manager: "Home Depot Product Authority, LLC"},
    Tld { name: ".theater", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".theatre", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".tiaa", category: "generic", manager: "Teachers Insurance and Annuity Association of America"},
    Tld { name: ".tickets", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".tienda", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".tips", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".tires", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".tirol", category: "generic", manager: "punkt Tirol GmbH"},
    Tld { name: ".tj", category: "country-code", manager: "Information Technology Center"},
    Tld { name: ".tjmaxx", category: "generic", manager: "The TJX Companies, Inc."},
    Tld { name: ".tk", category: "country-code", manager: "Telecommunication Tokelau Corporation (Teletok)"},
    Tld { name: ".tkmaxx", category: "generic", manager: "The TJX Companies, Inc."},
    Tld { name: ".tl", category: "country-code", manager: "Autoridade Nacional de Comunicações"},
    Tld { name: ".tm", category: "country-code", manager: "TM Domain Registry Ltd"},
    Tld { name: ".tmall", category: "generic", manager: "Alibaba Group Holding Limited"},
    Tld { name: ".tn", category: "country-code", manager: "Agence Tunisienne d'Internet"},
    Tld { name: ".to", category: "country-code", manager: "Government of the Kingdom of Tonga H.R.H. Crown Prince Tupouto'a c/o Consulate of Tonga"},
    Tld { name: ".today", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".tokyo", category: "generic", manager: "GMO Registry, Inc."},
    Tld { name: ".tools", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".top", category: "generic", manager: "Jiangsu Bangning Science & Technology Co.,Ltd."},
    Tld { name: ".tours", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".town", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".toys", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".tp", category: "country-code", manager: "Not assigned"},
    Tld { name: ".tr", category: "country-code", manager: "Bilgi Teknolojileri ve İletişim Kurumu (BTK)"},
    Tld { name: ".trade", category: "generic", manager: "Elite Registry Limited"},
    Tld { name: ".trading", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".training", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".travelersinsurance", category: "generic", manager: "Travelers TLD, LLC"},
    Tld { name: ".trust", category: "generic", manager: "Internet Naming Co."},
    Tld { name: ".trv", category: "generic", manager: "Travelers TLD, LLC"},
    Tld { name: ".tt", category: "country-code", manager: "University of the West Indies Faculty of Engineering"},
    Tld { name: ".tube", category: "generic", manager: "Latin American Telecom LLC"},
    Tld { name: ".tunes", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".tushu", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".tv", category: "country-code", manager: "Ministry of Justice, Communications and Foreign Affairs"},
    Tld { name: ".tw", category: "country-code", manager: "Taiwan Network Information Center (TWNIC)"},
    Tld { name: ".tz", category: "country-code", manager: "Tanzania Communications Regulatory Authority"},
    Tld { name: ".ua", category: "country-code", manager: "Hostmaster Ltd."},
    Tld { name: ".ubank", category: "generic", manager: "National Australia Bank Limited"},
    Tld { name: ".ug", category: "country-code", manager: "Uganda Online Ltd."},
    Tld { name: ".uk", category: "country-code", manager: "Nominet UK"},
    Tld { name: ".um", category: "country-code", manager: "Not assigned"},
    Tld { name: ".university", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".uno", category: "generic", manager: "Radix Technologies Inc."},
    Tld { name: ".us", category: "country-code", manager: "Registry Services, LLC"},
    Tld { name: ".uy", category: "country-code", manager: "SeCIU - Universidad de la Republica"},
    Tld { name: ".uz", category: "country-code", manager: "Single Integrator for Creation and Support of State Information Systems UZINFOCOM"},
    Tld { name: ".va", category: "country-code", manager: "Holy See - Vatican City State"},
    Tld { name: ".vacations", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".vana", category: "generic", manager: "Internet Naming Co."},
    Tld { name: ".vc", category: "country-code", manager: "Ministry of Telecommunications, Science, Technology and Industry"},
    Tld { name: ".ve", category: "country-code", manager: "Comisión Nacional de Telecomunicaciones (CONATEL)"},
    Tld { name: ".vegas", category: "generic", manager: "Dot Vegas, Inc."},
    Tld { name: ".ventures", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".versicherung", category: "generic", manager: "tldbox GmbH"},
    Tld { name: ".vet", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".vg", category: "country-code", manager: "Telecommunications Regulatory Commission of the Virgin Islands"},
    Tld { name: ".vi", category: "country-code", manager: "Virgin Islands Public Telecommunications System, Inc."},
    Tld { name: ".viajes", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".video", category: "generic", manager: "Dog Beach, LLC"},
    Tld { name: ".villas", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".vin", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".vip", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".vision", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".viva", category: "generic", manager: "Saudi Telecom Company"},
    Tld { name: ".vlaanderen", category: "generic", manager: "DNS.be vzw"},
    Tld { name: ".vn", category: "country-code", manager: "Viet Nam Internet Network Information Center (VNNIC)"},
    Tld { name: ".vodka", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".vote", category: "generic", manager: "Monolith Registry LLC"},
    Tld { name: ".voting", category: "generic", manager: "Valuetainment Corp."},
    Tld { name: ".voto", category: "generic", manager: "Monolith Registry LLC"},
    Tld { name: ".voyage", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".vu", category: "country-code", manager: "Telecommunications Radiocommunications and Broadcasting Regulator (TRBR)"},
    Tld { name: ".wales", category: "generic", manager: "Nominet UK"},
    Tld { name: ".wang", category: "generic", manager: "Zodiac Wang Limited"},
    Tld { name: ".wanggou", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".watch", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".watches", category: "generic", manager: "Identity Digital Limited"},
    Tld { name: ".weather", category: "generic", manager: "International Business Machines Corporation"},
    Tld { name: ".webcam", category: "generic", manager: "dot Webcam Limited"},
    Tld { name: ".website", category: "generic", manager: "Radix Technologies Inc."},
    Tld { name: ".wed", category: "generic", manager: "Emergency Back-End Registry Operator Program - ICANN"},
    Tld { name: ".wedding", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".weibo", category: "generic", manager: "Sina Corporation"},
    Tld { name: ".wf", category: "country-code", manager: "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)"},
    Tld { name: ".whoswho", category: "generic", manager: "Who's Who Registry"},
    Tld { name: ".wien", category: "generic", manager: "punkt.wien GmbH"},
    Tld { name: ".wiki", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".win", category: "generic", manager: "First Registry Limited"},
    Tld { name: ".wine", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".winners", category: "generic", manager: "The TJX Companies, Inc."},
    Tld { name: ".work", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".works", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".world", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".wow", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".ws", category: "country-code", manager: "Government of Samoa Ministry of Foreign Affairs & Trade"},
    Tld { name: ".wtf", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".xihuan", category: "generic", manager: "QIHOO 360 TECHNOLOGY CO. LTD."},
    Tld { name: ".xin", category: "generic", manager: "Elegant Leader Limited"},
    Tld { name: ".xyz", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".yachts", category: "generic", manager: "XYZ.COM LLC"},
    Tld { name: ".ye", category: "country-code", manager: "TeleYemen"},
    Tld { name: ".yoga", category: "generic", manager: "Registry Services, LLC"},
    Tld { name: ".yokohama", category: "generic", manager: "GMO Registry, Inc."},
    Tld { name: ".you", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".yt", category: "country-code", manager: "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)"},
    Tld { name: ".yun", category: "generic", manager: "QIHOO 360 TECHNOLOGY CO. LTD."},
    Tld { name: ".za", category: "country-code", manager: "ZA Domain Name Authority"},
    Tld { name: ".zero", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { name: ".zip", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { name: ".zm", category: "country-code", manager: "Zambia Information and Communications Technology Authority (ZICTA"},
    Tld { name: ".zone", category: "generic", manager: "Binky Moon, LLC"},
    Tld { name: ".zuerich", category: "generic", manager: "Kanton Zürich (Canton of Zurich)"},
    Tld { name: ".zw", category: "country-code", manager: "Postal and Telecommunications Regulatory Authority of Zimbabwe (POTRAZ)"},
];
