use serde::Serialize;
use typeshare::typeshare;

#[typeshare]
#[derive(Serialize)]
pub(crate) struct Tld {
    pub domain: &'static str,
    pub category: &'static str,
    pub manager: &'static str,
}

pub(crate) const TLDS: &[Tld] = &[
    Tld { domain: ".able", category: "generic", manager: "Able Inc."},
    Tld { domain: ".abogado", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".abudhabi", category: "generic", manager: "Abu Dhabi Systems and Information Centre"},
    Tld { domain: ".ac", category: "country-code", manager: "Internet Computer Bureau Limited"},
    Tld { domain: ".academy", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".accountant", category: "generic", manager: "dot Accountant Limited"},
    Tld { domain: ".accountants", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".actor", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".ad", category: "country-code", manager: "Andorra Telecom"},
    Tld { domain: ".ads", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".adult", category: "generic", manager: "ICM Registry AD LLC"},
    Tld { domain: ".ae", category: "country-code", manager: "Telecommunications and Digital Government Regulatory Authority (TDRA)"},
    Tld { domain: ".af", category: "country-code", manager: "Ministry of Communications and IT"},
    Tld { domain: ".africa", category: "generic", manager: "ZA Central Registry NPC trading as Registry.Africa"},
    Tld { domain: ".ag", category: "country-code", manager: "UHSA School of Medicine"},
    Tld { domain: ".agency", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".ai", category: "country-code", manager: "Government of Anguilla"},
    Tld { domain: ".airforce", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".al", category: "country-code", manager: "Electronic and Postal Communications Authority - AKEP"},
    Tld { domain: ".alsace", category: "generic", manager: "REGION GRAND EST"},
    Tld { domain: ".am", category: "country-code", manager: "Internet Society Non-governmental Organization"},
    Tld { domain: ".americanfamily", category: "generic", manager: "AmFam, Inc."},
    Tld { domain: ".amfam", category: "generic", manager: "AmFam, Inc."},
    Tld { domain: ".amsterdam", category: "generic", manager: "Gemeente Amsterdam"},
    Tld { domain: ".an", category: "country-code", manager: "Not assigned"},
    Tld { domain: ".analytics", category: "generic", manager: "Campus IP LLC"},
    Tld { domain: ".anquan", category: "generic", manager: "QIHOO 360 TECHNOLOGY CO. LTD."},
    Tld { domain: ".ao", category: "country-code", manager: "Ministry of Telecommunications and Information Technologies (MTTI)"},
    Tld { domain: ".apartments", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".app", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".aq", category: "country-code", manager: "Antarctica Network Information Centre Limited"},
    Tld { domain: ".ar", category: "country-code", manager: "Presidencia de la Nación – Secretaría Legal y Técnica"},
    Tld { domain: ".arab", category: "generic", manager: "League of Arab States"},
    Tld { domain: ".archi", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".army", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".arpa", category: "infrastructure", manager: "Internet Architecture Board (IAB)"},
    Tld { domain: ".art", category: "generic", manager: "UK Creative Ideas Limited"},
    Tld { domain: ".arte", category: "generic", manager: "Association Relative à la Télévision Européenne G.E.I.E."},
    Tld { domain: ".as", category: "country-code", manager: "AS Domain Registry"},
    Tld { domain: ".asda", category: "generic", manager: "Wal-Mart Stores, Inc."},
    Tld { domain: ".associates", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".at", category: "country-code", manager: "nic.at GmbH"},
    Tld { domain: ".athleta", category: "generic", manager: "The Gap, Inc."},
    Tld { domain: ".attorney", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".au", category: "country-code", manager: ".au Domain Administration (auDA)"},
    Tld { domain: ".auction", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".audible", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".audio", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".author", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".auto", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".autos", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".aw", category: "country-code", manager: "SETAR"},
    Tld { domain: ".ax", category: "country-code", manager: "Ålands landskapsregering"},
    Tld { domain: ".az", category: "country-code", manager: "IntraNS"},
    Tld { domain: ".ba", category: "country-code", manager: "Universtiy Telinformatic Centre (UTIC)"},
    Tld { domain: ".baby", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".banamex", category: "generic", manager: "Citigroup Inc."},
    Tld { domain: ".band", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".bank", category: "generic", manager: "fTLD Registry Services, LLC"},
    Tld { domain: ".bar", category: "generic", manager: "Punto 2012 Sociedad Anonima Promotora de Inversion de Capital Variable"},
    Tld { domain: ".barcelona", category: "generic", manager: "Municipi de Barcelona"},
    Tld { domain: ".barefoot", category: "generic", manager: "Gallo Vineyards, Inc."},
    Tld { domain: ".bargains", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".baseball", category: "generic", manager: "MLB Advanced Media DH, LLC"},
    Tld { domain: ".bayern", category: "generic", manager: "Bayern Connect GmbH"},
    Tld { domain: ".bb", category: "country-code", manager: "Ministry of Innovation, Science and Smart Technology"},
    Tld { domain: ".bcn", category: "generic", manager: "Municipi de Barcelona"},
    Tld { domain: ".bd", category: "country-code", manager: "Posts and Telecommunications Division"},
    Tld { domain: ".be", category: "country-code", manager: "DNS Belgium vzw/asbl"},
    Tld { domain: ".beats", category: "generic", manager: "Beats Electronics, LLC"},
    Tld { domain: ".beauty", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".beer", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".berlin", category: "generic", manager: "dotBERLIN GmbH & Co. KG"},
    Tld { domain: ".best", category: "generic", manager: "BestTLD Pty Ltd"},
    Tld { domain: ".bestbuy", category: "generic", manager: "BBY Solutions, Inc."},
    Tld { domain: ".bet", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".bf", category: "country-code", manager: "Autorité de Régulation des Communications Electroniques et des Postes (ARCEP)"},
    Tld { domain: ".bg", category: "country-code", manager: "Register.BG"},
    Tld { domain: ".bh", category: "country-code", manager: "Telecommunications Regulatory Authority (TRA)"},
    Tld { domain: ".bi", category: "country-code", manager: "Centre National de l'Informatique"},
    Tld { domain: ".bible", category: "generic", manager: "American Bible Society"},
    Tld { domain: ".bid", category: "generic", manager: "dot Bid Limited"},
    Tld { domain: ".bike", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".bingo", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".bio", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".biz", category: "generic-restricted", manager: "Registry Services, LLC"},
    Tld { domain: ".bj", category: "country-code", manager: "Autorité de Régulation des Communications Electroniques et de la Poste du Bénin (ARCEP BENIN)"},
    Tld { domain: ".bl", category: "country-code", manager: "Not assigned"},
    Tld { domain: ".black", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".blackfriday", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".blockbuster", category: "generic", manager: "Dish DBS Corporation"},
    Tld { domain: ".blog", category: "generic", manager: "Knock Knock WHOIS There, LLC"},
    Tld { domain: ".blue", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".bm", category: "country-code", manager: "Registry General Department, Ministry of Home Affairs"},
    Tld { domain: ".bn", category: "country-code", manager: "Authority for Info-communications Technology Industry of Brunei Darussalam (AITI)"},
    Tld { domain: ".bo", category: "country-code", manager: "Agencia para el Desarrollo de la Información de la Sociedad en Bolivia"},
    Tld { domain: ".boats", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".bofa", category: "generic", manager: "Bank of America Corporation"},
    Tld { domain: ".bom", category: "generic", manager: "Núcleo de Informação e Coordenação do Ponto BR - NIC.br"},
    Tld { domain: ".boo", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".book", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".boston", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".bot", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".boutique", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".box", category: "generic", manager: "Intercap Registry Inc."},
    Tld { domain: ".bq", category: "country-code", manager: "Not assigned"},
    Tld { domain: ".br", category: "country-code", manager: "Comite Gestor da Internet no Brasil"},
    Tld { domain: ".broadway", category: "generic", manager: "Celebrate Broadway, Inc."},
    Tld { domain: ".broker", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".brussels", category: "generic", manager: "DNS.be vzw"},
    Tld { domain: ".bs", category: "country-code", manager: "University of The Bahamas"},
    Tld { domain: ".bt", category: "country-code", manager: "Ministry of Information and Communications"},
    Tld { domain: ".build", category: "generic", manager: "Plan Bee LLC"},
    Tld { domain: ".builders", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".business", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".buy", category: "generic", manager: "Amazon Registry Services, INC"},
    Tld { domain: ".buzz", category: "generic", manager: "DOTSTRATEGY CO."},
    Tld { domain: ".bv", category: "country-code", manager: "Norid A/S"},
    Tld { domain: ".bw", category: "country-code", manager: "Botswana Communications Regulatory Authority (BOCRA)"},
    Tld { domain: ".by", category: "country-code", manager: "Belarusian Cloud Technologies LLC"},
    Tld { domain: ".bz", category: "country-code", manager: "University of Belize"},
    Tld { domain: ".bzh", category: "generic", manager: "Association www.bzh"},
    Tld { domain: ".ca", category: "country-code", manager: "Canadian Internet Registration Authority (CIRA) Autorité Canadienne pour les enregistrements Internet (ACEI)"},
    Tld { domain: ".cab", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".cafe", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".call", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".cam", category: "generic", manager: "CAM Connecting SARL"},
    Tld { domain: ".camera", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".camp", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".capetown", category: "generic", manager: "ZA Central Registry NPC trading as ZA Central Registry"},
    Tld { domain: ".capital", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".car", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".cards", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".care", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".career", category: "generic", manager: "dotCareer LLC"},
    Tld { domain: ".careers", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".cars", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".casa", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".case", category: "generic", manager: "Digity, LLC"},
    Tld { domain: ".cash", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".casino", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".catering", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".catholic", category: "generic", manager: "Pontificium Consilium de Comunicationibus Socialibus (PCCS) (Pontifical Council for Social Communication)"},
    Tld { domain: ".cc", category: "country-code", manager: "eNIC Cocos (Keeling) Islands Pty. Ltd. d/b/a Island Internet Services"},
    Tld { domain: ".cd", category: "country-code", manager: "Office Congolais des Postes et Télécommunications - OCPT"},
    Tld { domain: ".center", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".ceo", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".cf", category: "country-code", manager: "Societe Centrafricaine de Telecommunications (SOCATEL)"},
    Tld { domain: ".cfd", category: "generic", manager: "DOTCFD REGISTRY LTD"},
    Tld { domain: ".cg", category: "country-code", manager: "Interpoint Switzerland"},
    Tld { domain: ".ch", category: "country-code", manager: "SWITCH The Swiss Education & Research Network"},
    Tld { domain: ".channel", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".charity", category: "generic", manager: "Public Interest Registry (PIR)"},
    Tld { domain: ".chat", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".cheap", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".christmas", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".church", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".ci", category: "country-code", manager: "Autorité de Régulation des Télécommunications/TIC de Côte d’lvoire (ARTCI)"},
    Tld { domain: ".circle", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".city", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".ck", category: "country-code", manager: "Telecom Cook Islands Ltd."},
    Tld { domain: ".cl", category: "country-code", manager: "NIC Chile (University of Chile)"},
    Tld { domain: ".claims", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".cleaning", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".click", category: "generic", manager: "Internet Naming Co."},
    Tld { domain: ".clinic", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".clinique", category: "generic", manager: "The Estée Lauder Companies Inc."},
    Tld { domain: ".clothing", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".cloud", category: "generic", manager: "ARUBA PEC S.p.A."},
    Tld { domain: ".club", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".cm", category: "country-code", manager: "Agence Nationale des Technologies de l'Information et de la Communication (ANTIC)"},
    Tld { domain: ".cn", category: "country-code", manager: "China Internet Network Information Center (CNNIC)"},
    Tld { domain: ".co", category: "country-code", manager: "Ministry of Information and Communications Technologies (MinTIC)"},
    Tld { domain: ".coach", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".codes", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".coffee", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".college", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".cologne", category: "generic", manager: "dotKoeln GmbH"},
    Tld { domain: ".com", category: "generic", manager: "VeriSign Global Registry Services"},
    Tld { domain: ".community", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".company", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".compare", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".computer", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".comsec", category: "generic", manager: "VeriSign, Inc."},
    Tld { domain: ".condos", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".construction", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".consulting", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".contact", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".contractors", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".cooking", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".cool", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".corsica", category: "generic", manager: "Collectivité de Corse"},
    Tld { domain: ".country", category: "generic", manager: "Internet Naming Co."},
    Tld { domain: ".coupon", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".coupons", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".courses", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".cpa", category: "generic", manager: "American Institute of Certified Public Accountants"},
    Tld { domain: ".cr", category: "country-code", manager: "National Academy of Sciences Academia Nacional de Ciencias"},
    Tld { domain: ".credit", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".creditcard", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".cricket", category: "generic", manager: "dot Cricket Limited"},
    Tld { domain: ".cruise", category: "generic", manager: "Viking River Cruises (Bermuda) Ltd."},
    Tld { domain: ".cruises", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".cu", category: "country-code", manager: "CENIAInternet Industria y San Jose Capitolio Nacional"},
    Tld { domain: ".cv", category: "country-code", manager: "Agência Reguladora Multissectorial da Economia (ARME)"},
    Tld { domain: ".cw", category: "country-code", manager: "University of Curacao"},
    Tld { domain: ".cx", category: "country-code", manager: "Christmas Island Domain Administration Limited"},
    Tld { domain: ".cy", category: "country-code", manager: "University of Cyprus"},
    Tld { domain: ".cymru", category: "generic", manager: "Nominet UK"},
    Tld { domain: ".cyou", category: "generic", manager: "Shortdot SA"},
    Tld { domain: ".cz", category: "country-code", manager: "CZ.NIC, z.s.p.o"},
    Tld { domain: ".dad", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".dance", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".data", category: "generic", manager: "Dish DBS Corporation"},
    Tld { domain: ".date", category: "generic", manager: "dot Date Limited"},
    Tld { domain: ".dating", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".day", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".dclk", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".dds", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".de", category: "country-code", manager: "DENIC eG"},
    Tld { domain: ".deal", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".deals", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".degree", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".delivery", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".democrat", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".dental", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".dentist", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".desi", category: "generic", manager: "Emergency Back-End Registry Operator Program - ICANN"},
    Tld { domain: ".design", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".dev", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".diamonds", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".diet", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".digital", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".direct", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".directory", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".discount", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".diy", category: "generic", manager: "Internet Naming Co."},
    Tld { domain: ".dj", category: "country-code", manager: "Djibouti Telecom S.A"},
    Tld { domain: ".dk", category: "country-code", manager: "Dansk Internet Forum"},
    Tld { domain: ".dm", category: "country-code", manager: "DotDM Corporation"},
    Tld { domain: ".do", category: "country-code", manager: "Pontificia Universidad Catolica Madre y Maestra Recinto Santo Tomas de Aquino"},
    Tld { domain: ".docs", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".doctor", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".dog", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".domains", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".dot", category: "generic", manager: "Dish DBS Corporation"},
    Tld { domain: ".download", category: "generic", manager: "dot Support Limited"},
    Tld { domain: ".drive", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".dtv", category: "generic", manager: "Dish DBS Corporation"},
    Tld { domain: ".dubai", category: "generic", manager: "Dubai Smart Government Department"},
    Tld { domain: ".durban", category: "generic", manager: "ZA Central Registry NPC trading as ZA Central Registry"},
    Tld { domain: ".dvr", category: "generic", manager: "Hughes Satellite Systems Corporation"},
    Tld { domain: ".dz", category: "country-code", manager: "CERIST"},
    Tld { domain: ".earth", category: "generic", manager: "Interlink Systems Innovation Institute K.K."},
    Tld { domain: ".eat", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".ec", category: "country-code", manager: "ECUADORDOMAIN S.A."},
    Tld { domain: ".eco", category: "generic", manager: "Big Room Inc."},
    Tld { domain: ".education", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".ee", category: "country-code", manager: "Eesti Interneti Sihtasutus (EIS)"},
    Tld { domain: ".eg", category: "country-code", manager: "Egyptian Universities Network (EUN) Supreme Council of Universities"},
    Tld { domain: ".eh", category: "country-code", manager: "Not assigned"},
    Tld { domain: ".email", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".energy", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".engineer", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".engineering", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".enterprises", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".equipment", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".er", category: "country-code", manager: "Eritrea Telecommunication Services Corporation (EriTel)"},
    Tld { domain: ".es", category: "country-code", manager: "Red.es"},
    Tld { domain: ".esq", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".estate", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".et", category: "country-code", manager: "Ethio telecom"},
    Tld { domain: ".eu", category: "country-code", manager: "EURid vzw/asbl"},
    Tld { domain: ".eus", category: "generic", manager: "Puntueus Fundazioa"},
    Tld { domain: ".events", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".exchange", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".expert", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".exposed", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".express", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".fail", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".faith", category: "generic", manager: "dot Faith Limited"},
    Tld { domain: ".family", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".fan", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".fans", category: "generic", manager: "ZDNS International Limited"},
    Tld { domain: ".farm", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".fashion", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".fast", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".feedback", category: "generic", manager: "Top Level Spectrum, Inc."},
    Tld { domain: ".fi", category: "country-code", manager: "Finnish Transport and Communications Agency Traficom"},
    Tld { domain: ".fido", category: "generic", manager: "Rogers Communications Canada Inc."},
    Tld { domain: ".film", category: "generic", manager: "Motion Picture Domain Registry Pty Ltd"},
    Tld { domain: ".final", category: "generic", manager: "Núcleo de Informação e Coordenação do Ponto BR - NIC.br"},
    Tld { domain: ".finance", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".financial", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".fire", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".fish", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".fishing", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".fit", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".fitness", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".fj", category: "country-code", manager: "The University of the South Pacific IT Services"},
    Tld { domain: ".fk", category: "country-code", manager: "Falkland Islands Government"},
    Tld { domain: ".flights", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".florist", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".flowers", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".fly", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".fm", category: "country-code", manager: "FSM Telecommunications Corporation"},
    Tld { domain: ".fo", category: "country-code", manager: "FO Council"},
    Tld { domain: ".foo", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".food", category: "generic", manager: "Internet Naming Co."},
    Tld { domain: ".football", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".forsale", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".forum", category: "generic", manager: "Fegistry, LLC"},
    Tld { domain: ".foundation", category: "generic", manager: "Public Interest Registry (PIR)"},
    Tld { domain: ".fr", category: "country-code", manager: "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)"},
    Tld { domain: ".free", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".frl", category: "generic", manager: "FRLregistry B.V."},
    Tld { domain: ".ftr", category: "generic", manager: "Frontier Communications Corporation"},
    Tld { domain: ".fun", category: "generic", manager: "Radix Technologies Inc."},
    Tld { domain: ".fund", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".furniture", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".futbol", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".fyi", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".ga", category: "country-code", manager: "Agence Nationale des Infrastructures Numériques et des Fréquences (ANINF)"},
    Tld { domain: ".gal", category: "generic", manager: "Asociación puntoGAL"},
    Tld { domain: ".gallery", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".game", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".games", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".garden", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".gay", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".gb", category: "country-code", manager: "Reserved Domain - IANA"},
    Tld { domain: ".gd", category: "country-code", manager: "The National Telecommunications Regulatory Commission (NTRC)"},
    Tld { domain: ".gdn", category: "generic", manager: "Joint Stock Company Navigation-information systems"},
    Tld { domain: ".ge", category: "country-code", manager: "Caucasus Online LLC"},
    Tld { domain: ".gent", category: "generic", manager: "Combell nv"},
    Tld { domain: ".george", category: "generic", manager: "Wal-Mart Stores, Inc."},
    Tld { domain: ".gf", category: "country-code", manager: "CANAL+ TELECOM"},
    Tld { domain: ".gg", category: "country-code", manager: "Island Networks Ltd."},
    Tld { domain: ".ggee", category: "generic", manager: "GMO Internet, Inc."},
    Tld { domain: ".gh", category: "country-code", manager: "Network Computer Systems Limited"},
    Tld { domain: ".gi", category: "country-code", manager: "Sapphire Networks"},
    Tld { domain: ".gift", category: "generic", manager: "Uniregistry, Corp."},
    Tld { domain: ".gifts", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".gives", category: "generic", manager: "Public Interest Registry (PIR)"},
    Tld { domain: ".gl", category: "country-code", manager: "TELE Greenland A/S"},
    Tld { domain: ".glass", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".global", category: "generic", manager: "Dot Global Domain Registry Limited"},
    Tld { domain: ".gm", category: "country-code", manager: "GM-NIC"},
    Tld { domain: ".gmbh", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".gn", category: "country-code", manager: "Centre National des Sciences Halieutiques de Boussoura"},
    Tld { domain: ".gold", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".golf", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".goo", category: "generic", manager: "NTT Resonant Inc."},
    Tld { domain: ".gop", category: "generic", manager: "Republican State Leadership Committee, Inc."},
    Tld { domain: ".got", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".gp", category: "country-code", manager: "Networking Technologies Group"},
    Tld { domain: ".gq", category: "country-code", manager: "GETESA"},
    Tld { domain: ".gr", category: "country-code", manager: "ICS-FORTH GR"},
    Tld { domain: ".graphics", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".gratis", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".green", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".gripe", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".grocery", category: "generic", manager: "Wal-Mart Stores, Inc."},
    Tld { domain: ".group", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".gs", category: "country-code", manager: "Government of South Georgia and South Sandwich Islands (GSGSSI)"},
    Tld { domain: ".gt", category: "country-code", manager: "Universidad del Valle de Guatemala"},
    Tld { domain: ".gu", category: "country-code", manager: "University of Guam"},
    Tld { domain: ".guge", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".guide", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".guitars", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".guru", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".gw", category: "country-code", manager: "Autoridade Reguladora Nacional - Tecnologias de Informação e Comunicação da Guiné-Bissau"},
    Tld { domain: ".gy", category: "country-code", manager: "University of Guyana"},
    Tld { domain: ".hair", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".hamburg", category: "generic", manager: "Hamburg Top-Level-Domain GmbH"},
    Tld { domain: ".hangout", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".haus", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".health", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".healthcare", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".help", category: "generic", manager: "Innovation Service Ltd"},
    Tld { domain: ".helsinki", category: "generic", manager: "City of Helsinki"},
    Tld { domain: ".here", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".hiphop", category: "generic", manager: "Dot Hip Hop, LLC"},
    Tld { domain: ".hiv", category: "generic", manager: "Internet Naming Co."},
    Tld { domain: ".hk", category: "country-code", manager: "Hong Kong Internet Registration Corporation Ltd."},
    Tld { domain: ".hm", category: "country-code", manager: "HM Domain Registry"},
    Tld { domain: ".hn", category: "country-code", manager: "Red de Desarrollo Sostenible Honduras"},
    Tld { domain: ".hockey", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".holdings", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".holiday", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".homedepot", category: "generic", manager: "Home Depot Product Authority, LLC"},
    Tld { domain: ".homegoods", category: "generic", manager: "The TJX Companies, Inc."},
    Tld { domain: ".homes", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".homesense", category: "generic", manager: "The TJX Companies, Inc."},
    Tld { domain: ".horse", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".hospital", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".host", category: "generic", manager: "Radix Technologies Inc."},
    Tld { domain: ".hosting", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".hot", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".hotels", category: "generic", manager: "Booking.com B.V."},
    Tld { domain: ".house", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".how", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".hr", category: "country-code", manager: "CARNet - Croatian Academic and Research Network"},
    Tld { domain: ".ht", category: "country-code", manager: "Consortium FDS/RDDH"},
    Tld { domain: ".hu", category: "country-code", manager: "Council of Hungarian Internet Providers (CHIP)"},
    Tld { domain: ".icbc", category: "generic", manager: "Industrial and Commercial Bank of China Limited"},
    Tld { domain: ".ice", category: "generic", manager: "IntercontinentalExchange, Inc."},
    Tld { domain: ".icu", category: "generic", manager: "Shortdot SA"},
    Tld { domain: ".id", category: "country-code", manager: "Perkumpulan Pengelola Nama Domain Internet Indonesia (PANDI)"},
    Tld { domain: ".ie", category: "country-code", manager: "University College Dublin Computing Services Computer Centre"},
    Tld { domain: ".il", category: "country-code", manager: "The Israel Internet Association (RA)"},
    Tld { domain: ".im", category: "country-code", manager: "Isle of Man Government"},
    Tld { domain: ".imamat", category: "generic", manager: "Fondation Aga Khan (Aga Khan Foundation)"},
    Tld { domain: ".immo", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".immobilien", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".in", category: "country-code", manager: "National Internet Exchange of India"},
    Tld { domain: ".inc", category: "generic", manager: "Intercap Registry Inc."},
    Tld { domain: ".industries", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".info", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".ing", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".ink", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".institute", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".insurance", category: "generic", manager: "fTLD Registry Services LLC"},
    Tld { domain: ".insure", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".international", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".investments", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".io", category: "country-code", manager: "Internet Computer Bureau Limited"},
    Tld { domain: ".iq", category: "country-code", manager: "Communications and Media Commission (CMC)"},
    Tld { domain: ".ir", category: "country-code", manager: "Institute for Research in Fundamental Sciences"},
    Tld { domain: ".irish", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".is", category: "country-code", manager: "ISNIC - Internet Iceland ltd."},
    Tld { domain: ".ismaili", category: "generic", manager: "Fondation Aga Khan (Aga Khan Foundation)"},
    Tld { domain: ".ist", category: "generic", manager: "Istanbul Metropolitan Municipality"},
    Tld { domain: ".istanbul", category: "generic", manager: "Istanbul Metropolitan Municipality"},
    Tld { domain: ".it", category: "country-code", manager: "IIT - CNR"},
    Tld { domain: ".je", category: "country-code", manager: "Island Networks (Jersey) Ltd."},
    Tld { domain: ".jetzt", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".jewelry", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".jio", category: "generic", manager: "Affinity Names, Inc."},
    Tld { domain: ".jll", category: "generic", manager: "Jones Lang LaSalle Incorporated"},
    Tld { domain: ".jm", category: "country-code", manager: "University of West Indies"},
    Tld { domain: ".jmp", category: "generic", manager: "Matrix IP LLC"},
    Tld { domain: ".jnj", category: "generic", manager: "Johnson & Johnson Services, Inc."},
    Tld { domain: ".jo", category: "country-code", manager: "Ministry of Digital Economy and Entrepreneurship (MoDEE)"},
    Tld { domain: ".joburg", category: "generic", manager: "ZA Central Registry NPC trading as ZA Central Registry"},
    Tld { domain: ".jot", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".joy", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".jp", category: "country-code", manager: "Japan Registry Services Co., Ltd."},
    Tld { domain: ".jprs", category: "generic", manager: "Japan Registry Services Co., Ltd."},
    Tld { domain: ".juegos", category: "generic", manager: "Internet Naming Company LLC"},
    Tld { domain: ".kaufen", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".ke", category: "country-code", manager: "Kenya Network Information Center (KeNIC)"},
    Tld { domain: ".kg", category: "country-code", manager: "AsiaInfo Telecommunication Enterprise"},
    Tld { domain: ".kh", category: "country-code", manager: "Telecommunication Regulator of Cambodia (TRC)"},
    Tld { domain: ".ki", category: "country-code", manager: "Ministry of Information, Communications and Transport (MICT)"},
    Tld { domain: ".kids", category: "generic", manager: "DotKids Foundation Limited"},
    Tld { domain: ".kim", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".kitchen", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".kiwi", category: "generic", manager: "DOT KIWI LIMITED"},
    Tld { domain: ".km", category: "country-code", manager: "Comores Telecom"},
    Tld { domain: ".kn", category: "country-code", manager: "Ministry of Finance, Sustainable Development Information & Technology"},
    Tld { domain: ".koeln", category: "generic", manager: "dotKoeln GmbH"},
    Tld { domain: ".kosher", category: "generic", manager: "Kosher Marketing Assets LLC"},
    Tld { domain: ".kp", category: "country-code", manager: "Star Joint Venture Company"},
    Tld { domain: ".kpn", category: "generic", manager: "Koninklijke KPN N.V."},
    Tld { domain: ".kr", category: "country-code", manager: "Korea Internet & Security Agency (KISA)"},
    Tld { domain: ".krd", category: "generic", manager: "KRG Department of Information Technology"},
    Tld { domain: ".kw", category: "country-code", manager: "Communications and Information Technology Regulatory Authority"},
    Tld { domain: ".ky", category: "country-code", manager: "Utility Regulation and Competition Office (OfReg)"},
    Tld { domain: ".kyoto", category: "generic", manager: "Academic Institution: Kyoto Jyoho Gakuen"},
    Tld { domain: ".kz", category: "country-code", manager: "Association of IT Companies of Kazakhstan"},
    Tld { domain: ".la", category: "country-code", manager: "Lao National Internet Center (LANIC), Ministry of Technology and Communications"},
    Tld { domain: ".lamer", category: "generic", manager: "The Estée Lauder Companies Inc."},
    Tld { domain: ".land", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".lat", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".latino", category: "generic", manager: "Dish DBS Corporation"},
    Tld { domain: ".law", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".lawyer", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".lb", category: "country-code", manager: "Internet Society Lebanon"},
    Tld { domain: ".lc", category: "country-code", manager: "University of Puerto Rico"},
    Tld { domain: ".lease", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".lefrak", category: "generic", manager: "LeFrak Organization, Inc."},
    Tld { domain: ".legal", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".lgbt", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".li", category: "country-code", manager: "SWITCH The Swiss Education & Research Network"},
    Tld { domain: ".life", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".lifeinsurance", category: "generic", manager: "American Council of Life Insurers"},
    Tld { domain: ".lighting", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".like", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".limited", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".limo", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".link", category: "generic", manager: "Nova Registry Ltd."},
    Tld { domain: ".live", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".living", category: "generic", manager: "Internet Naming Co."},
    Tld { domain: ".lk", category: "country-code", manager: "Council for Information Technology LK Domain Registrar"},
    Tld { domain: ".llc", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".llp", category: "generic", manager: "Intercap Registry Inc."},
    Tld { domain: ".loan", category: "generic", manager: "dot Loan Limited"},
    Tld { domain: ".loans", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".locker", category: "generic", manager: "Orange Domains LLC"},
    Tld { domain: ".lol", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".london", category: "generic", manager: "Dot London Domains Limited"},
    Tld { domain: ".lotto", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".love", category: "generic", manager: "Merchant Law Group LLP"},
    Tld { domain: ".lr", category: "country-code", manager: "Data Technology Solutions, Inc."},
    Tld { domain: ".ls", category: "country-code", manager: "Lesotho Network Information Centre Proprietary (LSNIC)"},
    Tld { domain: ".lt", category: "country-code", manager: "Kaunas University of Technology"},
    Tld { domain: ".ltd", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".ltda", category: "generic", manager: "InterNetX Corp."},
    Tld { domain: ".lu", category: "country-code", manager: "RESTENA"},
    Tld { domain: ".luxe", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".luxury", category: "generic", manager: "Luxury Partners LLC"},
    Tld { domain: ".lv", category: "country-code", manager: "University of Latvia Institute of Mathematics and Computer Science Department of Network Solutions (DNS)"},
    Tld { domain: ".ly", category: "country-code", manager: "General Post and Telecommunication Company"},
    Tld { domain: ".ma", category: "country-code", manager: "Agence Nationale de Réglementation des Télécommunications (ANRT)"},
    Tld { domain: ".madrid", category: "generic", manager: "Comunidad de Madrid"},
    Tld { domain: ".maison", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".makeup", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".management", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".map", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".market", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".marketing", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".markets", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".marshalls", category: "generic", manager: "The TJX Companies, Inc."},
    Tld { domain: ".mba", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".mc", category: "country-code", manager: "Direction des Plateformes et des Ressources Numériques"},
    Tld { domain: ".md", category: "country-code", manager: "IP Serviciul Tehnologia Informatiei si Securitate Cibernetica"},
    Tld { domain: ".me", category: "country-code", manager: "Government of Montenegro"},
    Tld { domain: ".med", category: "generic", manager: "Medistry LLC"},
    Tld { domain: ".media", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".meet", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".melbourne", category: "generic", manager: "The Crown in right of the State of Victoria, represented by its Department of State Development, Business and Innovation"},
    Tld { domain: ".meme", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".memorial", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".men", category: "generic", manager: "Exclusive Registry Limited"},
    Tld { domain: ".menu", category: "generic", manager: "Dot Menu Registry LLC"},
    Tld { domain: ".merckmsd", category: "generic", manager: "MSD Registry Holdings, Inc."},
    Tld { domain: ".mf", category: "country-code", manager: "Not assigned"},
    Tld { domain: ".mg", category: "country-code", manager: "NIC-MG (Network Information Center Madagascar)"},
    Tld { domain: ".mh", category: "country-code", manager: "Office of the Cabinet"},
    Tld { domain: ".miami", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".mint", category: "generic", manager: "Intuit Administrative Services, Inc."},
    Tld { domain: ".mk", category: "country-code", manager: "Macedonian Academic Research Network Skopje"},
    Tld { domain: ".ml", category: "country-code", manager: "Agence des Technologies de l’Information et de la Communication"},
    Tld { domain: ".mls", category: "generic", manager: "The Canadian Real Estate Association"},
    Tld { domain: ".mm", category: "country-code", manager: "Ministry of Transport and Communications"},
    Tld { domain: ".mn", category: "country-code", manager: "Datacom Co., Ltd."},
    Tld { domain: ".mo", category: "country-code", manager: "Macao Post and Telecommunications Bureau (CTT)"},
    Tld { domain: ".mobi", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".mobile", category: "generic", manager: "Dish DBS Corporation"},
    Tld { domain: ".moda", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".moe", category: "generic", manager: "Interlink Systems Innovation Institute K.K."},
    Tld { domain: ".moi", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".mom", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".money", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".monster", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".mortgage", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".moscow", category: "generic", manager: "Foundation for Assistance for Internet Technologies and Infrastructure Development (FAITID)"},
    Tld { domain: ".motorcycles", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".mov", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".movie", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".mp", category: "country-code", manager: "Saipan Datacom, Inc."},
    Tld { domain: ".mq", category: "country-code", manager: "CANAL+ TELECOM"},
    Tld { domain: ".mr", category: "country-code", manager: "Université de Nouakchott Al Aasriya"},
    Tld { domain: ".ms", category: "country-code", manager: "MNI Networks Ltd."},
    Tld { domain: ".mt", category: "country-code", manager: "NIC (Malta)"},
    Tld { domain: ".mu", category: "country-code", manager: "Internet Direct Ltd"},
    Tld { domain: ".music", category: "generic", manager: "DotMusic Limited"},
    Tld { domain: ".mv", category: "country-code", manager: "Dhiraagu Pvt. Ltd. (DHIVEHINET)"},
    Tld { domain: ".mw", category: "country-code", manager: "Malawi Sustainable Development Network Programme (Malawi SDNP)"},
    Tld { domain: ".mx", category: "country-code", manager: "NIC-Mexico ITESM - Campus Monterrey"},
    Tld { domain: ".my", category: "country-code", manager: "MYNIC Berhad"},
    Tld { domain: ".mz", category: "country-code", manager: "Centro de Informatica de Universidade Eduardo Mondlane"},
    Tld { domain: ".na", category: "country-code", manager: "Namibian Network Information Center"},
    Tld { domain: ".nab", category: "generic", manager: "National Australia Bank Limited"},
    Tld { domain: ".nagoya", category: "generic", manager: "GMO Registry, Inc."},
    Tld { domain: ".name", category: "generic-restricted", manager: "VeriSign Information Services, Inc."},
    Tld { domain: ".navy", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".nc", category: "country-code", manager: "Office des Postes et Telecommunications"},
    Tld { domain: ".ne", category: "country-code", manager: "SONITEL"},
    Tld { domain: ".net", category: "generic", manager: "VeriSign Global Registry Services"},
    Tld { domain: ".netbank", category: "generic", manager: "COMMONWEALTH BANK OF AUSTRALIA"},
    Tld { domain: ".network", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".new", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".news", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".next", category: "generic", manager: "Next plc"},
    Tld { domain: ".nextdirect", category: "generic", manager: "Next plc"},
    Tld { domain: ".nexus", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".nf", category: "country-code", manager: "Norfolk Island Data Services"},
    Tld { domain: ".ng", category: "country-code", manager: "Nigeria Internet Registration Association"},
    Tld { domain: ".ngo", category: "generic", manager: "Public Interest Registry"},
    Tld { domain: ".ni", category: "country-code", manager: "Universidad Nacional del Ingernieria Centro de Computo"},
    Tld { domain: ".ninja", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".nl", category: "country-code", manager: "SIDN (Stichting Internet Domeinregistratie Nederland)"},
    Tld { domain: ".no", category: "country-code", manager: "Norid A/S"},
    Tld { domain: ".now", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".nowruz", category: "generic", manager: "Asia Green IT System Bilgisayar San. ve Tic. Ltd. Sti."},
    Tld { domain: ".nowtv", category: "generic", manager: "Starbucks (HK) Limited"},
    Tld { domain: ".np", category: "country-code", manager: "Mercantile Communications Pvt. Ltd."},
    Tld { domain: ".nr", category: "country-code", manager: "CENPAC NET"},
    Tld { domain: ".nrw", category: "generic", manager: "Minds + Machines GmbH"},
    Tld { domain: ".nu", category: "country-code", manager: "The IUSN Foundation"},
    Tld { domain: ".nyc", category: "generic", manager: "The City of New York by and through the New York City Department of Information Technology & Telecommunications"},
    Tld { domain: ".nz", category: "country-code", manager: "InternetNZ"},
    Tld { domain: ".observer", category: "generic", manager: "Fegistry, LLC"},
    Tld { domain: ".okinawa", category: "generic", manager: "BRregistry, Inc."},
    Tld { domain: ".olayan", category: "generic", manager: "Crescent Holding GmbH"},
    Tld { domain: ".olayangroup", category: "generic", manager: "Crescent Holding GmbH"},
    Tld { domain: ".ollo", category: "generic", manager: "Dish DBS Corporation"},
    Tld { domain: ".om", category: "country-code", manager: "Telecommunications Regulatory Authority (TRA)"},
    Tld { domain: ".one", category: "generic", manager: "One.com A/S"},
    Tld { domain: ".ong", category: "generic", manager: "Public Interest Registry"},
    Tld { domain: ".onl", category: "generic", manager: "iRegistry GmbH"},
    Tld { domain: ".online", category: "generic", manager: "Radix Technologies Inc."},
    Tld { domain: ".ooo", category: "generic", manager: "INFIBEAM INCORPORATION LIMITED"},
    Tld { domain: ".open", category: "generic", manager: "American Express Travel Related Services Company, Inc."},
    Tld { domain: ".org", category: "generic", manager: "Public Interest Registry (PIR)"},
    Tld { domain: ".organic", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".origins", category: "generic", manager: "The Estée Lauder Companies Inc."},
    Tld { domain: ".osaka", category: "generic", manager: "Osaka Registry Co., Ltd."},
    Tld { domain: ".ott", category: "generic", manager: "Dish DBS Corporation"},
    Tld { domain: ".pa", category: "country-code", manager: "Universidad Tecnologica de Panama"},
    Tld { domain: ".page", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".paris", category: "generic", manager: "City of Paris"},
    Tld { domain: ".pars", category: "generic", manager: "Asia Green IT System Bilgisayar San. ve Tic. Ltd. Sti."},
    Tld { domain: ".partners", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".parts", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".party", category: "generic", manager: "Blue Sky Registry Limited"},
    Tld { domain: ".pay", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".pe", category: "country-code", manager: "Red Cientifica Peruana"},
    Tld { domain: ".pet", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".pf", category: "country-code", manager: "Gouvernement de la Polynésie française"},
    Tld { domain: ".pg", category: "country-code", manager: "PNG DNS Administration Vice Chancellors Office The Papua New Guinea University of Technology"},
    Tld { domain: ".ph", category: "country-code", manager: "PH Domain Foundation"},
    Tld { domain: ".pharmacy", category: "generic", manager: "National Association of Boards of Pharmacy"},
    Tld { domain: ".phd", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".phone", category: "generic", manager: "Dish DBS Corporation"},
    Tld { domain: ".photo", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".photography", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".photos", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".physio", category: "generic", manager: "PhysBiz Pty Ltd"},
    Tld { domain: ".pics", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".pictures", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".pid", category: "generic", manager: "Top Level Spectrum, Inc."},
    Tld { domain: ".pin", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".pink", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".pizza", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".pk", category: "country-code", manager: "PKNIC"},
    Tld { domain: ".pl", category: "country-code", manager: "Research and Academic Computer Network"},
    Tld { domain: ".place", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".plumbing", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".plus", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".pm", category: "country-code", manager: "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)"},
    Tld { domain: ".pn", category: "country-code", manager: "Pitcairn Island Administration"},
    Tld { domain: ".pnc", category: "generic", manager: "PNC Domain Co., LLC"},
    Tld { domain: ".poker", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".pr", category: "country-code", manager: "Gauss Research Laboratory Inc."},
    Tld { domain: ".pramerica", category: "generic", manager: "Prudential Financial, Inc."},
    Tld { domain: ".press", category: "generic", manager: "Radix Technologies Inc."},
    Tld { domain: ".prime", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".pro", category: "generic-restricted", manager: "Identity Digital Limited"},
    Tld { domain: ".productions", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".prof", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".promo", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".properties", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".property", category: "generic", manager: "Digital Property Infrastructure Limited"},
    Tld { domain: ".protection", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".ps", category: "country-code", manager: "Ministry Of Telecommunications & Information Technology, Government Computer Center."},
    Tld { domain: ".pt", category: "country-code", manager: "Associação DNS.PT"},
    Tld { domain: ".pub", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".pw", category: "country-code", manager: "Micronesia Investment and Development Corporation"},
    Tld { domain: ".py", category: "country-code", manager: "NIC-PY"},
    Tld { domain: ".qa", category: "country-code", manager: "Communications Regulatory Authority"},
    Tld { domain: ".qpon", category: "generic", manager: "DOTQPON LLC."},
    Tld { domain: ".quebec", category: "generic", manager: "PointQuébec Inc"},
    Tld { domain: ".racing", category: "generic", manager: "Premier Registry Limited"},
    Tld { domain: ".radio", category: "generic", manager: "European Broadcasting Union (EBU)"},
    Tld { domain: ".re", category: "country-code", manager: "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)"},
    Tld { domain: ".read", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".realestate", category: "generic", manager: "dotRealEstate LLC"},
    Tld { domain: ".realtor", category: "generic", manager: "Real Estate Domains LLC"},
    Tld { domain: ".realty", category: "generic", manager: "Internet Naming Co."},
    Tld { domain: ".recipes", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".red", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".redumbrella", category: "generic", manager: "Travelers TLD, LLC"},
    Tld { domain: ".rehab", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".reise", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".reisen", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".reit", category: "generic", manager: "National Association of Real Estate Investment Trusts, Inc."},
    Tld { domain: ".ren", category: "generic", manager: "ZDNS International Limited"},
    Tld { domain: ".rent", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".rentals", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".repair", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".report", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".republican", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".rest", category: "generic", manager: "Punto 2012 Sociedad Anonima Promotora de Inversion de Capital Variable"},
    Tld { domain: ".restaurant", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".review", category: "generic", manager: "dot Review Limited"},
    Tld { domain: ".reviews", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".rich", category: "generic", manager: "iRegistry GmbH"},
    Tld { domain: ".richardli", category: "generic", manager: "Pacific Century Asset Management (HK) Limited"},
    Tld { domain: ".ril", category: "generic", manager: "Reliance Industries Limited"},
    Tld { domain: ".rio", category: "generic", manager: "Empresa Municipal de Informática SA - IPLANRIO"},
    Tld { domain: ".rip", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".ro", category: "country-code", manager: "National Institute for R&D in Informatics"},
    Tld { domain: ".rocks", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".rodeo", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".room", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".rs", category: "country-code", manager: "Serbian National Internet Domain Registry (RNIDS)"},
    Tld { domain: ".rsvp", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".ru", category: "country-code", manager: "Coordination Center for TLD RU"},
    Tld { domain: ".rugby", category: "generic", manager: "World Rugby Strategic Developments Limited"},
    Tld { domain: ".ruhr", category: "generic", manager: "dotSaarland GmbH"},
    Tld { domain: ".run", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".rw", category: "country-code", manager: "Rwanda Internet Community and Technology Alliance (RICTA) Ltd"},
    Tld { domain: ".ryukyu", category: "generic", manager: "BRregistry, Inc."},
    Tld { domain: ".sa", category: "country-code", manager: "Communications, Space and Technology Commission"},
    Tld { domain: ".saarland", category: "generic", manager: "dotSaarland GmbH"},
    Tld { domain: ".safe", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".sale", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".salon", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".samsclub", category: "generic", manager: "Wal-Mart Stores, Inc."},
    Tld { domain: ".sarl", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".save", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".sb", category: "country-code", manager: "Solomon Telekom Company Limited"},
    Tld { domain: ".sc", category: "country-code", manager: "VCS Pty Ltd"},
    Tld { domain: ".scholarships", category: "generic", manager: "Scholarships.com, LLC"},
    Tld { domain: ".school", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".schule", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".science", category: "generic", manager: "dot Science Limited"},
    Tld { domain: ".scot", category: "generic", manager: "Dot Scot Registry Limited"},
    Tld { domain: ".sd", category: "country-code", manager: "Sudan Internet Society"},
    Tld { domain: ".se", category: "country-code", manager: "The Internet Infrastructure Foundation"},
    Tld { domain: ".search", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".secure", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".security", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".select", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".services", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".sg", category: "country-code", manager: "Singapore Network Information Centre (SGNIC) Pte Ltd"},
    Tld { domain: ".sh", category: "country-code", manager: "Government of St. Helena"},
    Tld { domain: ".shia", category: "generic", manager: "Asia Green IT System Bilgisayar San. ve Tic. Ltd. Sti."},
    Tld { domain: ".shiksha", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".shoes", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".shop", category: "generic", manager: "GMO Registry, Inc."},
    Tld { domain: ".shopping", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".shouji", category: "generic", manager: "QIHOO 360 TECHNOLOGY CO. LTD."},
    Tld { domain: ".show", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".si", category: "country-code", manager: "Academic and Research Network of Slovenia (ARNES)"},
    Tld { domain: ".silk", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".singles", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".site", category: "generic", manager: "Radix Technologies Inc."},
    Tld { domain: ".sj", category: "country-code", manager: "Norid A/S"},
    Tld { domain: ".sk", category: "country-code", manager: "SK-NIC, a.s."},
    Tld { domain: ".ski", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".skin", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".sl", category: "country-code", manager: "Sierratel"},
    Tld { domain: ".sling", category: "generic", manager: "Hughes Satellite Systems Corporation"},
    Tld { domain: ".sm", category: "country-code", manager: "Telecom Italia San Marino S.p.A."},
    Tld { domain: ".smile", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".sn", category: "country-code", manager: "Universite Cheikh Anta Diop"},
    Tld { domain: ".so", category: "country-code", manager: "Ministry of Post and Telecommunications"},
    Tld { domain: ".soccer", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".social", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".software", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".solar", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".solutions", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".song", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".soy", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".spa", category: "generic", manager: "Asia Spa and Wellness Promotion Council Limited"},
    Tld { domain: ".space", category: "generic", manager: "Radix Technologies Inc."},
    Tld { domain: ".sport", category: "generic", manager: "SportAccord"},
    Tld { domain: ".spot", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".sr", category: "country-code", manager: "Telesur"},
    Tld { domain: ".srl", category: "generic", manager: "InterNetX Corp."},
    Tld { domain: ".ss", category: "country-code", manager: "National Communication Authority (NCA)"},
    Tld { domain: ".st", category: "country-code", manager: "Tecnisys"},
    Tld { domain: ".stockholm", category: "generic", manager: "Stockholms kommun"},
    Tld { domain: ".storage", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".store", category: "generic", manager: "Radix Technologies Inc."},
    Tld { domain: ".stream", category: "generic", manager: "dot Stream Limited"},
    Tld { domain: ".studio", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".study", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".style", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".su", category: "country-code", manager: "Russian Institute for Development of Public Networks (ROSNIIROS)"},
    Tld { domain: ".sucks", category: "generic", manager: "Vox Populi Registry Ltd."},
    Tld { domain: ".supplies", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".supply", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".support", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".surf", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".surgery", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".sv", category: "country-code", manager: "SVNet"},
    Tld { domain: ".swiss", category: "generic", manager: "Swiss Confederation"},
    Tld { domain: ".sx", category: "country-code", manager: "SX Registry SA B.V."},
    Tld { domain: ".sy", category: "country-code", manager: "National Agency for Network Services (NANS)"},
    Tld { domain: ".sydney", category: "generic", manager: "State of New South Wales, Department of Premier and Cabinet"},
    Tld { domain: ".systems", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".sz", category: "country-code", manager: "University of Swaziland Department of Computer Science"},
    Tld { domain: ".tab", category: "generic", manager: "Tabcorp Holdings Limited"},
    Tld { domain: ".taipei", category: "generic", manager: "Taipei City Government"},
    Tld { domain: ".talk", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".tatar", category: "generic", manager: "Limited Liability Company Coordination Center of Regional Domain of Tatarstan Republic"},
    Tld { domain: ".tattoo", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".tax", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".taxi", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".tc", category: "country-code", manager: "Melrex TC"},
    Tld { domain: ".tci", category: "generic", manager: "Asia Green IT System Bilgisayar San. ve Tic. Ltd. Sti."},
    Tld { domain: ".td", category: "country-code", manager: "l'Agence de Développement des Technologies de l'Information et de la Communication (ADETIC)"},
    Tld { domain: ".team", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".tech", category: "generic", manager: "Radix Technologies Inc."},
    Tld { domain: ".technology", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".tennis", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".tf", category: "country-code", manager: "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)"},
    Tld { domain: ".tg", category: "country-code", manager: "Autorité de Régulation des Communications Electroniques et des Postes (ARCEP)"},
    Tld { domain: ".th", category: "country-code", manager: "Thai Network Information Center Foundation"},
    Tld { domain: ".thd", category: "generic", manager: "Home Depot Product Authority, LLC"},
    Tld { domain: ".theater", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".theatre", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".tiaa", category: "generic", manager: "Teachers Insurance and Annuity Association of America"},
    Tld { domain: ".tickets", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".tienda", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".tips", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".tires", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".tirol", category: "generic", manager: "punkt Tirol GmbH"},
    Tld { domain: ".tj", category: "country-code", manager: "Information Technology Center"},
    Tld { domain: ".tjmaxx", category: "generic", manager: "The TJX Companies, Inc."},
    Tld { domain: ".tk", category: "country-code", manager: "Telecommunication Tokelau Corporation (Teletok)"},
    Tld { domain: ".tkmaxx", category: "generic", manager: "The TJX Companies, Inc."},
    Tld { domain: ".tl", category: "country-code", manager: "Autoridade Nacional de Comunicações"},
    Tld { domain: ".tm", category: "country-code", manager: "TM Domain Registry Ltd"},
    Tld { domain: ".tmall", category: "generic", manager: "Alibaba Group Holding Limited"},
    Tld { domain: ".tn", category: "country-code", manager: "Agence Tunisienne d'Internet"},
    Tld { domain: ".to", category: "country-code", manager: "Government of the Kingdom of Tonga H.R.H. Crown Prince Tupouto'a c/o Consulate of Tonga"},
    Tld { domain: ".today", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".tokyo", category: "generic", manager: "GMO Registry, Inc."},
    Tld { domain: ".tools", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".top", category: "generic", manager: "Jiangsu Bangning Science & Technology Co.,Ltd."},
    Tld { domain: ".tours", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".town", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".toys", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".tp", category: "country-code", manager: "Not assigned"},
    Tld { domain: ".tr", category: "country-code", manager: "Bilgi Teknolojileri ve İletişim Kurumu (BTK)"},
    Tld { domain: ".trade", category: "generic", manager: "Elite Registry Limited"},
    Tld { domain: ".trading", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".training", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".travelersinsurance", category: "generic", manager: "Travelers TLD, LLC"},
    Tld { domain: ".trust", category: "generic", manager: "Internet Naming Co."},
    Tld { domain: ".trv", category: "generic", manager: "Travelers TLD, LLC"},
    Tld { domain: ".tt", category: "country-code", manager: "University of the West Indies Faculty of Engineering"},
    Tld { domain: ".tube", category: "generic", manager: "Latin American Telecom LLC"},
    Tld { domain: ".tunes", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".tushu", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".tv", category: "country-code", manager: "Ministry of Justice, Communications and Foreign Affairs"},
    Tld { domain: ".tw", category: "country-code", manager: "Taiwan Network Information Center (TWNIC)"},
    Tld { domain: ".tz", category: "country-code", manager: "Tanzania Communications Regulatory Authority"},
    Tld { domain: ".ua", category: "country-code", manager: "Hostmaster Ltd."},
    Tld { domain: ".ubank", category: "generic", manager: "National Australia Bank Limited"},
    Tld { domain: ".ug", category: "country-code", manager: "Uganda Online Ltd."},
    Tld { domain: ".uk", category: "country-code", manager: "Nominet UK"},
    Tld { domain: ".um", category: "country-code", manager: "Not assigned"},
    Tld { domain: ".university", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".uno", category: "generic", manager: "Radix Technologies Inc."},
    Tld { domain: ".us", category: "country-code", manager: "Registry Services, LLC"},
    Tld { domain: ".uy", category: "country-code", manager: "SeCIU - Universidad de la Republica"},
    Tld { domain: ".uz", category: "country-code", manager: "Single Integrator for Creation and Support of State Information Systems UZINFOCOM"},
    Tld { domain: ".va", category: "country-code", manager: "Holy See - Vatican City State"},
    Tld { domain: ".vacations", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".vana", category: "generic", manager: "Internet Naming Co."},
    Tld { domain: ".vc", category: "country-code", manager: "Ministry of Telecommunications, Science, Technology and Industry"},
    Tld { domain: ".ve", category: "country-code", manager: "Comisión Nacional de Telecomunicaciones (CONATEL)"},
    Tld { domain: ".vegas", category: "generic", manager: "Dot Vegas, Inc."},
    Tld { domain: ".ventures", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".versicherung", category: "generic", manager: "tldbox GmbH"},
    Tld { domain: ".vet", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".vg", category: "country-code", manager: "Telecommunications Regulatory Commission of the Virgin Islands"},
    Tld { domain: ".vi", category: "country-code", manager: "Virgin Islands Public Telecommunications System, Inc."},
    Tld { domain: ".viajes", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".video", category: "generic", manager: "Dog Beach, LLC"},
    Tld { domain: ".villas", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".vin", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".vip", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".vision", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".viva", category: "generic", manager: "Saudi Telecom Company"},
    Tld { domain: ".vlaanderen", category: "generic", manager: "DNS.be vzw"},
    Tld { domain: ".vn", category: "country-code", manager: "Viet Nam Internet Network Information Center (VNNIC)"},
    Tld { domain: ".vodka", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".vote", category: "generic", manager: "Monolith Registry LLC"},
    Tld { domain: ".voting", category: "generic", manager: "Valuetainment Corp."},
    Tld { domain: ".voto", category: "generic", manager: "Monolith Registry LLC"},
    Tld { domain: ".voyage", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".vu", category: "country-code", manager: "Telecommunications Radiocommunications and Broadcasting Regulator (TRBR)"},
    Tld { domain: ".wales", category: "generic", manager: "Nominet UK"},
    Tld { domain: ".wang", category: "generic", manager: "Zodiac Wang Limited"},
    Tld { domain: ".wanggou", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".watch", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".watches", category: "generic", manager: "Identity Digital Limited"},
    Tld { domain: ".weather", category: "generic", manager: "International Business Machines Corporation"},
    Tld { domain: ".webcam", category: "generic", manager: "dot Webcam Limited"},
    Tld { domain: ".website", category: "generic", manager: "Radix Technologies Inc."},
    Tld { domain: ".wed", category: "generic", manager: "Emergency Back-End Registry Operator Program - ICANN"},
    Tld { domain: ".wedding", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".weibo", category: "generic", manager: "Sina Corporation"},
    Tld { domain: ".wf", category: "country-code", manager: "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)"},
    Tld { domain: ".whoswho", category: "generic", manager: "Who's Who Registry"},
    Tld { domain: ".wien", category: "generic", manager: "punkt.wien GmbH"},
    Tld { domain: ".wiki", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".win", category: "generic", manager: "First Registry Limited"},
    Tld { domain: ".wine", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".winners", category: "generic", manager: "The TJX Companies, Inc."},
    Tld { domain: ".work", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".works", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".world", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".wow", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".ws", category: "country-code", manager: "Government of Samoa Ministry of Foreign Affairs & Trade"},
    Tld { domain: ".wtf", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".xihuan", category: "generic", manager: "QIHOO 360 TECHNOLOGY CO. LTD."},
    Tld { domain: ".xin", category: "generic", manager: "Elegant Leader Limited"},
    Tld { domain: ".xyz", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".yachts", category: "generic", manager: "XYZ.COM LLC"},
    Tld { domain: ".ye", category: "country-code", manager: "TeleYemen"},
    Tld { domain: ".yoga", category: "generic", manager: "Registry Services, LLC"},
    Tld { domain: ".yokohama", category: "generic", manager: "GMO Registry, Inc."},
    Tld { domain: ".you", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".yt", category: "country-code", manager: "Association Française pour le Nommage Internet en Coopération (A.F.N.I.C.)"},
    Tld { domain: ".yun", category: "generic", manager: "QIHOO 360 TECHNOLOGY CO. LTD."},
    Tld { domain: ".za", category: "country-code", manager: "ZA Domain Name Authority"},
    Tld { domain: ".zero", category: "generic", manager: "Amazon Registry Services, Inc."},
    Tld { domain: ".zip", category: "generic", manager: "Charleston Road Registry Inc."},
    Tld { domain: ".zm", category: "country-code", manager: "Zambia Information and Communications Technology Authority (ZICTA)"},
    Tld { domain: ".zone", category: "generic", manager: "Binky Moon, LLC"},
    Tld { domain: ".zuerich", category: "generic", manager: "Kanton Zürich (Canton of Zurich)"},
    Tld { domain: ".zw", category: "country-code", manager: "Postal and Telecommunications Regulatory Authority of Zimbabwe (POTRAZ)"},
];
