[package]
name = "sh-core"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
axum = { workspace = true, features = ["query", "json"] }
serde = { version = "1.0", features = ["derive"] }
typeshare = { workspace = true }
phf = { version = "0.11.1", features = ["macros"] }
