[package]
name = "sh-core"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
axum  = { workspace = true, features = ["json"] }
typeshare = "1.0.2"
serde = { version = "1.0", features = ["derive"] }
