/*
 Generated by typeshare 1.8.0
*/

export interface ShortenParams {
	domain: string;
}

export interface Domain {
	name: string;
	tld: Tld;
	status: boolean;
}

export interface ShortenRes {
	domains: Domain[];
}

