/*
 Generated by typeshare 1.8.0
*/

export interface ShortenParams {
	domain: string;
}

export interface Tld {
	name: string;
	category: string;
	manager: string;
	server: string;
}

export interface Domain {
	name: string;
	tld: Tld;
	status: string;
}

export interface ShortenRes {
	domains: Domain[];
}

