[package]
name = "sh-scripts"
version = "0.1.0"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
# sh-crates
sh-crypto = { path = "../crates/crypto" }
sh-domain = { path = "../crates/domain" }

# workspace dependencies
tokio = { workspace = true, features = ["full"] }
dotenv = { workspace = true }

# specific scripts dependencies 
reqwest = { version = "0.12.5", features = ["json"] }
scraper = "0.19.1"
serde_json = "1.0.120"
flate2 = "1.0.30"
memmap2 = "0.9.4"
