name: Setup Node.js, pnpm and dependencies
description: Setup Node.js, pnpm and dependencies
runs:
    using: "composite"
    steps:
        - name: Install pnpm
          uses: pnpm/action-setup@v3
          with:
              version: 8.x.x

        - name: Install Node.js
          uses: actions/setup-node@v4
          with:
              check-latest: true
              node-version-file: ".nvmrc"

        - name: Install pnpm deps
          shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
          run: pnpm i --frozen-lockfile
