/*
 Generated by typeshare 1.8.0
*/

export interface ShortenArgs {
	domain: string;
}

export interface Tld {
	domain: string;
	category: string;
	manager: string;
}

export interface ShortenRes {
	domain_list: Tld[];
}

