/*
 Generated by typeshare 1.8.0
*/

export interface ShortenArgs {
	domain: string
}

export interface ShortenRes {
	message: string
}

export interface Tld {
	name: string
	category: string
	manager: string
}
