name: publish
on: [push]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        name: publish
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: login to amazon ecr
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: build, tag, and push image to amazon ecr
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  ECR_REPOSITORY: sh-server
                  IMAGE_TAG: ${{ github.sha }}
              run: |
                  docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./apps/server
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

            - name: update lambda function
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  ECR_REPOSITORY: sh-server
                  IMAGE_TAG: ${{ github.sha }}
              run: |
                  aws lambda update-function-code \
                    --function-name sh-server \
                    --image-uri "${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"

            - name: setup pnpm
              uses: ./.github/actions/setup-pnpm

            - name: setup rust
              uses: ./.github/actions/setup-rust

            - name: build
              run: pnpm build

            - name: publish web to cf pages
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_ACCOUNT_ID }}
                  projectName: shorter
                  directory: ./apps/web/build
