on: [push]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        name: Publish
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Build
              run: pnpm build

            - name: Publish to Cloudflare Workers
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_ACCOUNT_ID }}
                  workingDirectory: ./apps/server
