on: [push]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        name: Publish to Cloudflare
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js, pnpm and dependencies
              uses: ./.github/actions/setup-pnpm

            - name: Setup rust and cargo-watch
              uses: ./.github/actions/setup-rust

            - name: Setup aws credentials
              uses: ./.github/actions/setup-aws

            - name: Build
              run: pnpm build

            - name: Publish landing to cloudflare pages
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_ACCOUNT_ID }}
                  projectName: sh-landing
                  directory: ./apps/landing/build

            - name: Publish server to aws lambda
              run: |
                  cargo lambda deploy --iam-role arn:aws:iam::533267168525:role/lambda sh-server
