name: refresh domains and tlds

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch: # allows manual triggering

jobs:
    generate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js, pnpm and dependencies
              uses: ./.github/actions/setup-pnpm

            - name: run generation scripts
              env:
                  ICANN_USERNAME: ${{ secrets.ICANN_USERNAME }}
                  ICANN_PASSWORD: ${{ secrets.ICANN_PASSWORD }}
              run: |
                  pnpm gen:tlds
                  pnpm gen:domains

            - name: commit and push changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add .
                  git commit -m "refresh domains and tlds" || exit 0
                  git push
