name: refresh domains and tlds

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    generate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GH_PAT }}
                  fetch-depth: 0

            - name: Setup Node.js, pnpm and dependencies
              uses: ./.github/actions/setup-pnpm

            - name: Run generation scripts
              env:
                  ICANN_USERNAME: ${{ secrets.ICANN_USERNAME }}
                  ICANN_PASSWORD: ${{ secrets.ICANN_PASSWORD }}
              run: |
                  pnpm gen:tlds
                  pnpm gen:domains

            - name: Commit and push changes
              run: |
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add .
                  git commit -m "refresh domains and tlds" || exit 0
                  git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
